.circleci/config.yml, package.json, packages/contracts/contracts/ChugSplashRegistry.sol, packages/contracts/package.json, packages/core/package.json, packages/demo/package.json, packages/executor/package.json, packages/plugins/package.json, yarn.lock
Adds basic circle CI checks to prevent common issues like unnecessary
dependencies and uncommitted yarn.lock changes. Will also start running
tests as soon as we start adding them.
=> feat(ci): introduce basic circle CI checks

.changeset/real-insects-add.md, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/contracts/ChugSplashRegistry.sol, packages/contracts/src/ifaces.ts, packages/demo/hardhat.config.ts, packages/plugins/src/hardhat/tasks.ts
Brings back the ChugSplashManager contract. I realized that there's a
compelling argument for a separation of ownership. We can still get the
best of both worlds with the announceEvent pattern that makes it easy to
find events on the central registry.
=> feat(ct): bring back Manager

specs/executor-economics.md
Adds a page to the specs folder for executor economics.
=> feat(specs): add executor economics page

.changeset/green-dryers-raise.md, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/contracts/ChugSplashRegistry.sol, packages/contracts/contracts/IProxyAdapter.sol, packages/contracts/contracts/ProxyAdmin.sol
=> feat(ct): add `ProxyAdmin`

.changeset/friendly-worms-vanish.md, packages/contracts/contracts/IProxyAdapter.sol, packages/contracts/contracts/ProxyAdmin.sol, packages/contracts/contracts/ProxyUpdater.sol
Simplifies the ProxyUpdater significantly by moving the `setCode` logic to the ProxyAdmin.
=> fix(ct): move setCode logic from ProxyUpdater to ProxyAdmin

packages/contracts/contracts/ProxyAdmin.sol
Fixes build errors that slipped through before I modified branch
protections to require yarn-monorepo pass before anything gets merged.
=> fix(ct): build errors

.changeset/metal-rice-suffer.md, packages/contracts/contracts/IProxyAdapter.sol, packages/contracts/contracts/adapters/TransparentUpgradeableAdapter.sol
A simple adapter for the default proxy used by ChugSplash, which is OpenZeppelin's `TransparentUpgradeableProxy`.
=> feat(ct): add adapter for default proxy

.changeset/healthy-countries-teach.md, packages/contracts/contracts/ChugSplashManager.sol
Allows the project owner to claim ownership of the (default and non-standard) proxies from the ChugSplashManager.
Closes #51.
=> fix(ct): allow user to claim proxy ownership

.changeset/good-cows-fix.md, packages/contracts/contracts/ChugSplashManager.sol
Fixes a couple minor things with the `transferProxyOwnership` function in the Manager contract.
=> fix(ct): update `transferProxyOwnership` in `ChugSplashManager`

.changeset/twelve-ducks-promise.md, packages/plugins/src/hardhat/predeploys.ts
Fixes a bug in the deterministic factory deployment that would cause things to break when deploying to a non-hardhat node.
=> fix(plg): deterministic factory deploy bug

.changeset/nice-cougars-impress.md, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts
Moves the logic for executing a bundle into a separate CLI command so that it can be used by the executor.
=> Refactor Execution Logic Into Separate Command

.changeset/lemon-wolves-sing.md, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts
- Fixes an issue where `chugsplash-execute` was called incorrectly. 
- Fixes an issue where the types for `chugsplash-execute` were not properly defined (Note, I just set them to any to make sure it works for now. Would be good to improve this in the future).
=> Fix: chugsplash-execute incorrect typing

.changeset/kind-crews-complain.md, packages/executor/src/index.ts, packages/executor/src/utils/compile.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts
- Implements a minimal executor that runs against localhost
- Adds a new CLI parameter `local` to the `node`, `chugsplash-deploy`, and `test` commands which defaults to `true`. This argument determines if the execution command should be run by the CLI or delegated to a separate executor process. This is a stopgap measure to allow testing the executor while continuing to default to fully local deployments. In the future, we'll need to add logic to base this on the network the user is deploying too. 
- Refactors the `TASK_CHUGSPLASH_BUNDLE_REMOTE` task to compile the artifacts necessary to complete the bundle using only the output from running the compiler programmatically. Previously, helper functions pulled artifact data from files that aren't available to the executor.
Note that the …
=> Minimal Executor

.changeset/good-maps-run.md, .changeset/honest-shrimps-bake.md, packages/core/src/utils.ts, packages/executor/.gitignore, packages/executor/src/index.ts, packages/executor/src/utils/compile.ts, packages/executor/src/utils/etherscan.ts, packages/executor/src/utils/initialize.ts, packages/plugins/src/hardhat/artifacts.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/predeploys.ts, packages/plugins/src/hardhat/tasks.ts
This PR:
* Fixes a bug with the remote bundling logic
* Refactors redundant remote bundling and fetching logic
* Integrates Etherscan verification into the executor
=> fix: integrate etherscan verification into executor

.changeset/spicy-geckos-greet.md, packages/executor/.dockerignore, packages/executor/.env.example, packages/executor/Dockerfile, packages/executor/package.json, packages/executor/src/index.ts, packages/executor/tsconfig.json, packages/plugins/.gitignore
Adds Docker container configuration for the executor.
You'll need to install [Docker Desktop](https://www.docker.com/products/docker-desktop/) to test this feature locally. 
1. In the root directory run `yarn build`.
2. Navigate to the plugins directory and run a local node `npx hardhat node --local false`.
3. Navigate to the `executor` directory, make a copy of .env.example, rename it to .env, and fill in the values (the Amplitude API key is optional).
4. Build the container `yarn build-container`
5. Run the container `yarn run-container`
6. You should see the container start up and output some logs. After ~20 seconds, you'll see logs indicating that the test contract from the plugins package was executed. 
You can also try out deploying other projects with the executor using `npx …
=> Add Docker Configuration for Executor

.changeset/plenty-tigers-confess.md, packages/executor/.env.example, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts
- Removes the --local parameter. Instead, the chain id is checked and the execution is done locally if and only if the target network is hardhat. 
- Adds `HARDHAT_NETWORK` to the .env.example file for the executor
=> Remove --local parameter

.changeset/modern-toes-turn.md, .changeset/unlucky-wolves-work.md, packages/executor/.env.example, packages/executor/Dockerfile, packages/executor/package.json
This PR fixes the bug that causes Etherscan verification to fail. It does this by changing the executor's executable from ts-node to hardhat, which injects the correct HRE into the environment.
=> fix(ex): run the executor using the hre executable

.changeset/spicy-geese-roll.md, packages/demo/hardhat.config.ts, packages/executor/hardhat.config.ts, packages/plugins/dev.ts, packages/plugins/hardhat.config.ts, packages/plugins/src/hardhat/tasks.ts
Refactors the execution process so that bundle actions are executed in parallel to improve execution speed. 
Note that transaction queuing does not work when automining is enabled on the hardhat network. So if this PR is merged, then all users will be required to use interval mining when testing against the local hardhat network. If it's possible to detect the mining mode of the hardhat network, then we might want to dynamically choose parallel or synchronous execution based on that. This would allow us to support both modes. For the moment though, I think this is a reasonable restriction that we can revisit if/when we encounter a user that cares a lot about using automining.
=> Parallelize Execution Process

.changeset/ten-pugs-repair.md, packages/core/src/utils.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/execution.ts, packages/plugins/src/hardhat/tasks.ts, packages/plugins/src/hardhat/utils.ts, packages/plugins/src/messages.ts
This PR:
* Removes a couple things inside of the execute task that should be user-facing, and puts these into
a function called `postExecutionActions`.
* Changes the execute task's `bundleState` argument to `bundleId` so that the most recent `bundleState` is calculated within the execute task. This fixes a bug I was experiencing where an outdated bundleState was being used in the task
* Improves error handling in the execute task
=> fix(pg): update the chugsplash-execute hardhat task

.changeset/four-drinks-peel.md, packages/plugins/src/hardhat/artifacts.ts
Fixes a minor issue where the build info metadata is parsed as if it is JSON when it is not.
=> Fix: Minor Build Info Parsing Bug

.changeset/wild-rocks-decide.md, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/src/ifaces.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts
Adds a `--no-compile` flag to the `node`, `test`, `run`, `chugsplash-deploy`, `test-remote-execution`, and `chugsplash-propose` task. Speeds up deployments significantly in larger repos.
=> fix(pg): add noCompile flag to relevant hardhat tasks

.changeset/khaki-owls-return.md, packages/core/src/actions/bundle.ts, packages/plugins/src/hardhat/tasks.ts
Batches ~50-100 SetStorage actions per transaction depending on the network's block gas limit.
=> fix: batch SetStorage actions into larger transactions

.changeset/calm-students-type.md, packages/executor/src/utils/etherscan.ts
Prevents one request failure from halting the entire verification process.
=> fix(ex): wrap Etherscan verification attempts in try/catch blocks

.changeset/slimy-apes-brake.md, packages/core/src/utils.ts, packages/plugins/package.json, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/execution.ts, packages/plugins/src/hardhat/tasks.ts, yarn.lock
This PR removes the progress bar that monitors the number of actions that've been executed so far in a bundle. I chose to remove it since we now execute most of the actions at once at the very beginning of the bundle, which pretty much defeats the purpose of a progress bar.
=> fix(pg): remove progress bar on execution-related hardhat tasks

.changeset/fuzzy-chairs-lick.md, packages/contracts/contracts/ChugSplashBootLoader.sol, packages/contracts/contracts/DeterministicProxyOwner.sol, packages/contracts/src/constants.ts, packages/contracts/src/ifaces.ts, packages/core/src/languages/solidity/predeploys.ts, packages/core/src/utils.ts, packages/executor/src/utils/initialize.ts
This PR makes the ChugSplashRegistry proxy's address deterministic. This solves an issue where the addresses of the ChugSplash predeploys would change whenever a change to the ChugSplashManager was introduced. This would have made it difficult for identical contracts deployed using ChugSplash to share the same addresses across networks. For example, if we deployed the predeploys on Optimism, then made some changes to the ChugSplashManager, then deployed the predeploys on Ethereum, the addresses of the predeploys would be different across chains. Consequently, the addresses of identical contracts deployed by ChugSplash would be different too, since all addresses ultimately rely on the ChugSplashRegistry's proxy.
In order to address this issue, I made it so that the ChugSplashRegistry's …
=> fix(ct): make chugsplashregistry proxy's address deterministic

.changeset/chilled-maps-raise.md, packages/plugins/src/hardhat/tasks.ts
This task is no longer necessary since the same executor logic is used throughout the plugin.
=> fix(pg): remove the test-remote-execution task

.changeset/real-moons-count.md, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts
The executor can't be invoked more than once in a Hardhat task, which causes an error to be thrown if running e.g. `npx hardhat node --deploy-all`. This PR fixes this issue by spinning up only one executor maximum in a command.
=> fix(pg): deploy the executor once per cli command

.changeset/five-lemons-cry.md, packages/core/src/utils.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts
Adds basic support for upgrading contracts via the `chugsplash-upgrade` task and the `isUpgrade` flag on the `chugsplash-deploy` task. 
There are still some more complex upgrade cases which we will need to handle to make this a really robust feature. 
- This PR does not handle cases where only some contracts in a config file need to be upgraded. If you attempt to upgrade a contract where the implementation code has not changed, you will encounter an error `ChugSplashManager: implementation was not deployed correctly`. This is due to create2 returning a zero address for the implementation address (I believe) due to the generated address already being in use.
- For the same reason, this PR also does not handle cases where only ChugSplash config variables have changed.
- This PR does not …
=> Basic Support for Upgrades

.changeset/mean-parents-relate.md, packages/core/src/config/parse.ts, packages/core/src/utils.ts, packages/demo/chugsplash/SimpleStorage.config.ts, packages/executor/src/utils/etherscan.ts, packages/plugins/src/hardhat/deployments.ts
The `getDefaultProxyAddress` function (formerly known as `getProxyAddress`) was incorrectly being used to calculate the the proxy address in multiple packages. This was incorrect because it doesn't take into consideration that the user may have defined their own proxy address in the ChugSplash config, which means the default proxy wouldn't be used. This PR fixes this issue by using the `ContractConfig.address` member instead of calling `getDefaultProxyAddress`.
=> fix: replace incorrect use of the `getDefaultProxyAddress` function

.changeset/wise-pumpkins-rush.md, packages/core/src/config/parse.ts, packages/core/src/config/types.ts, packages/executor/src/utils/compile.ts, packages/executor/src/utils/etherscan.ts, packages/plugins/src/hardhat/tasks.ts, packages/plugins/src/hardhat/utils.ts
Also updates the logic that injects .env variables into the ChugSplash config by routing the env variables through the `loadParsedChugSplashConfig` function.
=> fix: update canonical config type usage

.changeset/famous-lemons-end.md, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/src/ifaces.ts, packages/contracts/test/ChugSplashManager.t.sol
The primary reason for this change is to support the following scenario, which is currently prevented by our use of create2. Say we have two contracts in the same ChugSplash config that have the same creation bytecode, but different runtime bytecode. For example, the two contracts could have an immutable variable with different values. Currently, the create2 call from the ChugSplashManager fails because only one of these addresses can be deployed at the deterministically calculated address. Using the `create` opcode solves this.
=> fix(ct): change implementation contract deployment from create2 to create

.changeset/funny-boats-sort.md, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/src/ifaces.ts, packages/contracts/test/ChugSplashManager.t.sol
This makes it easy to get the deployment transaction hash of these contracts when they're deployed by the ChugSplashManager, which we'll need when generating their deployment artifacts.
=> fix(ct): add events for default proxy and implementation contract deployment

README.md
- Makes the readme compliant with [Standard Readme](https://github.com/RichardLitt/standard-readme). This is just a good practice IMO, but not a huge deal. 
- Adds a few more sections to the readme which make it a little cleaner including a table of contents and a basic usage guide
=> fix(docs): Expand readme and make Standard Readme compliant

.changeset/twelve-seas-drop.md, packages/core/src/utils.ts, packages/plugins/README.md, packages/plugins/src/hardhat/execution.ts, packages/plugins/src/hardhat/tasks.ts, packages/plugins/src/messages.ts
Makes `configPath` a normal parameter on all tasks which we decided to do due to the new add proposer task requiring a different parameter to be positional. 
I'd still like to rename `--config-path`, but I didn't include that change in this because we haven't decided what to do with it.
=> fix(pg): Make configPath a normal parameter on all tasks

.changeset/sour-shrimps-work.md, packages/core/src/utils.ts, packages/executor/src/index.ts, packages/executor/src/utils/compile.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts, packages/plugins/src/hardhat/type-extensions.ts
This is a necessary change to support the `chugsplash-diff` task on the Hardhat network, since there was previously no way to retrieve the canonical config aside from committing to IPFS.
=> fix(pg): write canonical config to file system when using executing bundles locally

.changeset/hot-news-build.md, packages/contracts/contracts/ChugSplashBootLoader.sol, packages/contracts/contracts/ProxyInitializer.sol, packages/contracts/src/constants.ts, packages/contracts/src/ifaces.ts, packages/contracts/test/ChugSplashManager.t.sol, packages/contracts/test/ChugSplashRegistry.t.sol, packages/contracts/test/integration-tests.t.sol, packages/core/src/languages/solidity/predeploys.ts
To deploy a new version of the ChugSplash pre-deploy contracts, simply change the `CHUGSPLASH_SALT` value in `constants.ts` within the contracts package.
=> fix(ct): add a universal salt that makes it easy to deploy new versions of the ChugSplash pre-deploys

.changeset/chatty-geckos-check.md, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/src/ifaces.ts, packages/contracts/test/ChugSplashManager.t.sol
This ensures that the executor cannot lose money on a deployment, which was previously possible if a sizable `maxPriorityFeePerGas` was used.
=> fix(ct): use `tx.gasprice` instead of `block.basefee`

.changeset/tough-ladybugs-appear.md, packages/executor/.env.example, packages/executor/src/index.ts
Adds support for defining the executor's port with an environment variable. This is needed because the ports must be different when deploying multiple containers on AWS.
=> feat(exec): Support defining executor port with environment variable

.changeset/selfish-badgers-buy.md, packages/core/src/actions/execute.ts, packages/core/src/languages/solidity/predeploys.ts, packages/core/src/utils.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/execution.ts, packages/plugins/src/hardhat/tasks.ts
This PR changes all transactions to use EIP-1559 gas pricing mechanisms as long as the network supports it. This prevents transactions from stalling on Goerli, which was a common occurrence since EIP 1559 transactions were not being used by default on it.
=> fix(core): use EIP-1559 transactions if supported by the network

.changeset/wet-ads-juggle.md, packages/plugins/src/hardhat/tasks.ts
This logic is redundant because `initializeChugSplash` is called from the in-process executor.
=> fix(pg): remove logic that initialize chugsplash when starting hardhat node

.changeset/wet-ads-juggle.md, packages/plugins/src/hardhat/tasks.ts
This reverts commit dcc7c7bbc7c87e97977e5c3d6e6583691c2a6cdd, which mistakenly remove the `disableChugSplash` option from the Hardhat node task. This option must be included if, for example, a user wants to register a project on the stand-alone Hardhat network.
=> Revert "fix(pg): remove logic that initialize chugsplash when starting hardhat node"

.changeset/afraid-tables-itch.md, packages/executor/src/index.ts
The executor wasn't detecting old BundleApproved events on startup because `lastBlockNumber` was set to -1 instead of 0.
=> fix(ex): detect old approval events

.changeset/rich-elephants-exercise.md, packages/core/src/actions/deployments.ts, packages/core/src/execution/index.ts, packages/core/src/messages/index.ts, packages/core/src/tasks/index.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts
Previously, `npx hardhat test` was failing in the demo package due to an error that was caused by calling `hre.ethers.provider.network.name`. I'm not 100% sure about the cause of this, but it seems to be stemming from the '@nomiclabs/hardhat-ethers` package.
=> fix(core): use `getNetwork` to retrieve network name

.changeset/mean-mirrors-chew.md, packages/core/src/utils.ts
Fixes an issue where Array.at() is not always supported depending on the NodeJS version due to how new the function standard is. This PR ensures that the function is polyfilled, so that it can be used regardless of the environment.
=> fix(core): Ensure array.at() is always supported

.changeset/afraid-eels-repair.md, packages/core/src/actions/deployments.ts, packages/core/src/execution/index.ts, packages/core/src/messages/index.ts, packages/core/src/tasks/index.ts, packages/core/src/utils.ts
Now that we use `resolveNetworkName`, the `localhost` network is now `hardhat`, which makes the network name in error messages confusing.
=> fix(core): don't infer network name in error messages

.changeset/hungry-grapes-own.md, packages/contracts/contracts/ChugSplashDataTypes.sol, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/src/ifaces.ts, packages/contracts/test/ChugSplashManager.t.sol, packages/core/src/actions/bundle.ts, packages/core/src/actions/types.ts, packages/core/src/config/parse.ts, packages/core/src/fund.ts, packages/core/src/tasks/index.ts, packages/plugins/src/hardhat/deployments.ts
Previously, we were using `target` and `referenceName` to refer to a proxy's string name representation in ChugSplash. This PR changes all mentions of "target" to "reference name" for consistency.
=> fix(core,ct,pg): change `target` to `referenceName` everywhere

.changeset/angry-penguins-chew.md, packages/core/src/languages/solidity/storage.ts
Small improvement to the config error when didn't provide a definition for every variable in a contract. Was unclear if the message was referring to a variable that was in the contract but not in the config or if the variable was in the config but not in the contract.
=> fix(core): minor tweak to config error string

.changeset/chilled-ads-protect.md, packages/executor/src/index.ts
Adds a default port for the executor which eliminates the need to define an `EXECUTOR_PORT` environment variable.
=> fix(exec): Add default port for executor

.changeset/short-mangos-listen.md, packages/core/src/languages/solidity/storage.ts
Adds an additional recommendation to clear your contract compilation artifact cache if a variable is included in the ChugSplash config, but not found in the contract storage layout. 
I encountered an issue where my deployment of the optimism repo failed b/c old contract artifacts were cached and for some reason, hardhat failed to detect that they needed to be recompiled. The solution was to remove the old artifacts and recompile.
=> fix(core): Add additional recommendation to clear contract artifact cache if var not found in storage layout

.changeset/many-fireants-hug.md, packages/core/src/languages/solidity/storage.ts
'Compilation artifacts' could be confused for the `artifacts/` folder, so I changed the error messages to explicitly mention the `cache` folder that the user would need to delete
=> fix(core): slightly change error message wording

.changeset/lucky-steaks-run.md
A new release was not pushed for the core package because I did not include a changeset.
=> Bump Core Dependency Versions

.changeset/cuddly-balloons-carry.md, packages/contracts/src/ifaces.ts, packages/core/src/actions/artifacts.ts, packages/core/src/languages/solidity/compiler.ts, packages/core/src/languages/solidity/types.ts, packages/executor/src/utils/etherscan.ts, yarn.lock
Previously, the logic in `getMinimumCompilerInput` was returning an incomplete set of compiler inputs under a certain edge case. This PR fixes that issue by changing the logic inside `getMinimumCompilerInput` to rely on the autogenerated `metadata` field, which contains the list of source names used for a given contract.
This PR also adds logic that throws an error if there's an error during compilation in `getCanonicalConfigArtifacts`.
=> fix(core,ex): change minimum compiler input logic to fix bug that generated incomplete inputs

.changeset/orange-pants-double.md, packages/core/src/actions/artifacts.ts
This error message was never getting triggered because of the newly added `addEnumMembersToStorageLayout` function in `getBuildInfo`.
=> fix(core): move the 'missing storage layout error' from `getStorageLayout` to `getBuildInfo`

docs/hardhat/setup-project.md
Previously, we were instructing users to install @chugsplash/core in the Hardhat getting started guide. This isn't necessary, so I removed this step.
=> docs: remove unnecessary @chugsplash/core install step

.changeset/clean-kangaroos-camp.md, packages/executor/src/index.ts
It's no longer necessary to supply port as an environment variable. Port is now a default option which means that it can be set as an environment variable with the format SERVICE_NAME__PORT.
=> maint(exec): remove port environment variable

.changeset/ninety-drinks-wash.md, packages/core/src/tasks/index.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts
This PR fixes an issue where Hardhat networks that didn't use the default chain id, 31337, would freeze when calling any ChugSplash task.
=> fix(core,pg): remove hard-coded chain id 31337

.changeset/rich-cats-fry.md, packages/core/src/types.ts, packages/executor/src/index.ts, packages/plugins/src/executor.ts
Reverts chugsplash/chugsplash#481
This is because the log level bug does not seem to be fully resolved. This PR is causing our integration test suite for the foundry library to fail.
=> Revert "maint(exec): remove log level hack"

.changeset/popular-baboons-lay.md, packages/plugins/src/hardhat/tasks.ts
Fixes an issue introduced in #479 where deploying locally using the hardhat plugin would fail because ChugSplash had not been initialized yet.
=> fix(pg): Fix issue where ChugSplash not initialized when executing locally

.changeset/green-walls-drum.md, packages/core/src/actions/artifacts.ts, packages/core/src/actions/bundle.ts, packages/core/src/config/parse.ts, packages/core/src/config/types.ts, packages/core/src/languages/solidity/compiler.ts, packages/core/src/languages/solidity/storage.ts, packages/core/src/tasks/index.ts, packages/core/src/utils.ts, packages/executor/src/utils/etherscan.ts
Previously, we had logic that inferred constructor arguments based on a user's immutable variable definitions in their ChugSplash file. This was a brittle approach that became particularly unreliable when immutable variables are passed into the constructors of parent contracts.
This PR fixes that issue by allowing users to define a 'constructorArgs' field in their ChugSplash file. We perform checks to ensure that their constructor(s) are deterministic by parsing the AST nodes of each contract and its parent contracts.
=> feat(core): set immutable variables in the ChugSplash file via the constructorArgs field

.changeset/rich-gorillas-kiss.md, packages/plugins/chugsplash/hardhat/TransparentUpgradableUpgrade.config.ts, packages/plugins/chugsplash/hardhat/UUPSUpgradableUpgrade.config.ts, packages/plugins/package.json, packages/plugins/test/Transfer.spec.ts
This PR changes the deployer of the OpenZeppelin proxies in `Transfer.spec.ts` to ensure that the proxy addresses remain consistent with the addresses defined in the corresponding `externalProxy` fields.
=> fix(pg): make OpenZeppelin proxy addresses consistent in tests

.changeset/hungry-squids-arrive.md, docs/special-var-defs.md, packages/core/src/utils.ts
The preserve keyword can only be used for variables that:
1. Exist in the previous storage layout with the same name
2. Exist at the same storage slot key and offset
3. Have the same type
=> fix(core): validate usage of the preserve keyword

.changeset/brave-clocks-act.md, packages/core/src/config/parse.ts, packages/core/src/tasks/index.ts, packages/plugins/src/foundry/index.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts, packages/plugins/src/scripts/display-bundle-info.ts
Adds support for asynchronously resolved ChugSplash configs. Users will now be able to export an asynchronous function from their config file and our tooling will take care of resolving it internally. 
I was integrating [Gelato Relay](https://github.com/gelatodigital/relay-contracts) (which appears to be their primary focus right now, though it is not their core protocol) on the plane flight back and encountered a use case for this feature so I went ahead and implemented it. We may want to consider updating the docs to make this the recommended method of creating your config file b/c it is significantly more powerful. 
The Gelato Relay codebase includes some mock contracts used for testing. This is the config file I wrote to deploy them using the asynchronous config file feature. 
On a …
=> feat(core): Add support for async config files

packages/core/src/fund.ts
Calling [reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) on an empty array without an initial value causes an error to be thrown.
=> refactor(core): add initial value to reduce call

.changeset/fuzzy-emus-stare.md, docs/variables.md, packages/core/src/actions/bundle.ts, packages/core/src/languages/solidity/storage.ts, packages/core/src/utils.ts, packages/demo/contracts/HelloChugSplash.sol, packages/plugins/chugsplash/foundry/deploy.t.js, packages/plugins/contracts/Storage.sol, packages/plugins/test/Storage.spec.ts, packages/plugins/test/constants.ts, packages/plugins/test/foundry/ChugSplash.t.sol
Adds support for user-defined types
- Since the storage layout doesn't include information on the underlying type of user-defined types by default, I had to fetch the underlying type from the compiler output and inject it into the storage layout. 
- Note that while this feature adds support for user-defined types, we are limited to treating them like their underlying types.
=> feat(core): Add support for user defined types

packages/plugins/chugsplash/foundry/deploy.t.js, packages/plugins/contracts/Storage.sol, packages/plugins/test/Storage.spec.ts, packages/plugins/test/constants.ts, specs/chugsplash-config.md
- Adds a spec document for a valid ChugSplash config and it's variable inputs
- Adds a test for a nested dynamic array
Does not cover constructor arguments or other config options. I [created a ticket to address those](https://linear.app/chugsplash/issue/CHU-135/add-constructor-args-and-other-config-options-to-chugsplash-config) in this document as well.
=> docs: Add specification for ChugSplash config input types

packages/core/package.json, packages/core/src/config/parse.ts, packages/core/src/tasks/index.ts, packages/core/src/types.ts, packages/core/src/utils.ts, packages/plugins/foundry-contracts/ChugSplash.sol, packages/plugins/src/foundry/index.ts, packages/plugins/src/hardhat/artifacts.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts, packages/plugins/src/scripts/display-bundle-info.ts, packages/plugins/src/utils.ts, packages/plugins/test/Transfer.spec.ts, packages/plugins/test/Validation.spec.ts, packages/plugins/test/foundry/ChugSplash.t.sol
- Brings the rest of the config related validation into the parse config interface
- Replaces `readUserChugSpalshConfig` and `readParsedChugSplashConfig` with `readValidationChugSplashConfig` and `readUnvalidatedChugSplashConfig`
- Introduces a new global object pattern
In this PR, I introduce a new pattern where we initialize a set of global variables at the beginning of our tasks to avoid passing the variables through a long chain of functions. This pattern allows me to avoid doing a large refactor to make sure the `readParsedChugSplashConfig` has the necessary variables to perform the full validation. In the future, we can simplify our existing logic by adding additional variables to the global object and removing them as parameters from our functions.
This pattern does have an …
=> maint(core): Bring rest of config validation into the parse config interface

.changeset/new-apples-drive.md, packages/core/src/languages/solidity/iterator.ts
As of Solidity 0.8.18, mapping keys/values can have names. For example:
```
mapping(address user => uint balance) public balances;
```
This doesn't require any changes in our encoding logic, but I updated the documentation to acknowledge this new feature.
=> fix(core): update doc for mapping value label in encoding logic

.changeset/empty-bulldogs-hammer.md, packages/contracts/contracts/ChugSplashManager.sol, packages/plugins/chugsplash/hardhat/UUPSAccessControlUpgradableUpgrade.config.ts, packages/plugins/chugsplash/hardhat/UUPSOwnableUpgradableUpgrade.config.ts
Fixes an issue where we incorrectly calculate the executor and protocol fees which causes the user to be overcharged. 
This was originally reported as an [off-chain gas estimation issue in CHU-161](https://linear.app/chugsplash/issue/CHU-161/broken-gas-estimation-and-refund).
On the topic of fees, I saw [this table on the Gelatos network fees ](https://docs.gelato.network/developer-services/relay/payment-and-fees) which is just interesting. We might want to use it to inform how to set our fees on different networks.
=> fix(ct): Fix incorrect fee calculation

.changeset/three-spies-worry.md, packages/contracts/contracts/ChugSplashManager.sol
To support rollbacks, we now allow bundles to be approved if they've previously been completed or cancelled.
=> feat(ct): support rollbacks

.changeset/smart-dolphins-lay.md, packages/contracts/contracts/interfaces/IChugSplashManager.sol, packages/contracts/contracts/interfaces/IChugSplashRegistry.sol, packages/core/package.json, packages/core/src/config/parse.ts, packages/core/src/config/types.ts, packages/core/src/tasks/index.ts, packages/core/src/types.ts, packages/core/src/utils.ts, packages/plugins/foundry-contracts/ChugSplash.sol, packages/plugins/remappings.txt, packages/plugins/src/foundry/index.ts, packages/plugins/src/hardhat/artifacts.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts, packages/plugins/src/scripts/display-bundle-info.ts, packages/plugins/src/utils.ts, packages/plugins/test/Transfer.spec.ts, packages/plugins/test/foundry/ChugSplash.t.sol
- Adds support for other openzeppelin safety check options
- Moves `silent` and `stream` parameters onto the CRE (ChugSplashRuntimeEnvironment) and uses refactors all uses of them to reference the CRE.
I also updated the `chugsplashLog` function to handle more complex outputs and used that function to output some warnings when users enable the unsafe flags. In a followup PR, I'll be updating the rest of the parsing logic to output errors using the `chugsplashLog` function to make the overall UX better.
=> feat(core): Add support for other openzeppelin safety check options

packages/core/src/config/parse.ts, packages/core/src/utils.ts
Removes our logic for checking if a UUPS-proxied contract includes the `upgradeTo` function and replaces it with the OpenZeppelin safety check logic for this instead. 
Blocked by #573
=> maint(core): Use OpenZeppelin logic for UUPS upgradeTo check

packages/core/src/config/parse.ts, packages/core/src/tasks/index.ts, packages/core/src/types.ts, packages/core/src/utils.ts, packages/plugins/chugsplash/VariableValidation.config.ts, packages/plugins/src/foundry/index.ts, packages/plugins/src/hardhat/artifacts.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts, packages/plugins/src/utils.ts, packages/plugins/test/Transfer.spec.ts, packages/plugins/test/Validation.spec.ts
Refactors the parsing logic so that as many errors as possible are output at the same time.
There are a few cases where if a particular issue is detected, it actually stops the rest of the parsing logic from working properly without significant refactoring. In those cases, we continue to throw errors and stop execution but we will still output all errors detected up to that point.
=> feat(core): Display all parsing validation errors

packages/contracts/contracts/updaters/DefaultUpdater.sol, packages/contracts/contracts/updaters/OZUUPSUpdater.sol, packages/contracts/contracts/updaters/ProxyUpdater.sol, packages/core/src/config/parse.ts
Fixes a vulnerability where an attacker could set arbitrary storage slots during execution. The issue is caused by the fact that the updater can be publicly available if it takes more than one block to execute a deployment. So we need to have logic on the setStorage function which prevents some arbitrary third party from calling it. 
This vulnerability was handled when we introduced the Updater pattern by introducing the ChugSplashAdmin and restricting access to the setStorage function to only proxy admins or ChugSplash admins depending on the proxy type. The vulnerability appears to have been reintroduced when a change was made to how we handle the setStorage action.
I resolved the issue by moving the ChugSplashAdmin logic onto the base ProxyUpdater and using it to secure the setStorage …
=> fix(ct): Fix security vulnerability on setStorage function

.changeset/slimy-mugs-search.md, packages/core/src/utils.ts
OpenZeppelin's solidity-ast library, which we use throughout our codebase, hasn't been tested thoroughly for Solidity versions before 0.6.0. [Here's the link](https://github.com/OpenZeppelin/solidity-ast#solidity-versioning).
=> fix(core): restrict solidity versions to >0.5.x

packages/core/src/languages/solidity/predeploys.ts
Fixes a bug introduced in #583 where attempting to deploy the ChugSplash contracts against a network where they are already deployed will cause the program to cash. This prevents us from doing deployments against local networks and will also prevent us from spinning up executors against networks where the contracts have already been deployed.
=> fix(core): Fix initializeChugSplash failure on network where contracts are already deployed

.changeset/fluffy-jokes-teach.md, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts
Before this PR, running `npx hardhat test` on a config with an error in it would result in the process closing without any reason why. This PR changes the test task to display logs by default, with the optional `--silent` flag to hide them.
=> fix(pg): display ChugSplash errors and warnings by default when running Hardhat tests

.changeset/wet-lobsters-accept.md, packages/core/src/config/parse.ts, packages/core/src/languages/solidity/storage.ts
Fixes two bugs discovered when deploying a `no-proxy` contract.
First bug:
Encoding error resulted from calling `chugsplash-deploy` on the demo contract as a `no-proxy` kind without a `variables` field.
Second bug:
Parsing error resulted from the same situation as above, except with `variables: {}` in the `no-proxy` contract.
=> fix(core): fix a couple bugs when deploying no-proxy contracts

packages/plugins/test/ManagerUpgrade.spec.ts, specs/chugsplash-config.md
Completes the specification of the ChugSplash config file including:
- Specification for the constructor arguments
- Specification for the other input options
Also fixes a minor issue with the plugin package tests.
=> Spec: Add Constructor Arg Specification

packages/contracts/.solhint.json, packages/contracts/.solhintignore, packages/contracts/package.json, packages/contracts/scripts/slither.sh, packages/contracts/slither.config.json, yarn.lock
Adds Slither and solhint prettier plugin to the contracts package with the same configuration as the Optimism monorepo.
Note: This does not enable Slither during the CI process as there are quite a few errors and warnings from it that we may want to address first. I've created a separate ticket to do that.
=> maint(ct): Add Slither and solhint prettier plugin to contracts package

.changeset/curly-cycles-collect.md, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/contracts/ChugSplashManagerProxy.sol, packages/contracts/contracts/ChugSplashRegistry.sol, packages/core/src/constants.ts, packages/core/src/languages/solidity/predeploys.ts, packages/core/src/utils.ts, packages/plugins/test/ManagerUpgrade.spec.ts
- Adds Semver versioning to the ChugSplashManager
- Renames some variables throughout the codebase to make the manager versioning more clear.
- Updates the `managers` and `projects` mappings in the registry to use the `ChugSplashManagerProxy` contract type instead of the `ChugSplashManager` contract type which simplifies things a bit and makes the use of a proxy in front of the managers a bit more clear.
=> maint(ct): Add Semver to ChugSplashManager

packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/contracts/ChugSplashRegistry.sol, packages/contracts/contracts/ManagedService.sol, packages/contracts/src/ifaces.ts, packages/core/src/constants.ts, packages/core/src/languages/solidity/predeploys.ts, packages/core/src/utils.ts, packages/executor/src/index.ts, packages/plugins/src/foundry/index.ts, packages/plugins/src/hardhat/tasks.ts
We now use `AccessControl` in the `ManagedService` contract to keep track of executors, managed service proposers, and protocol payment recipients. This functionality was removed from the registry to make it as minimal as possible, since it won't be upgraded in the future.
Also, this PR removes the `initializer` function in the registry in favor of calling setter functions, like `setVersion`. This is because the `initializer` function could be called by anyone when the registry is initially deployed, which is a security hazard. We could add an `onlyOwner` modifier to the `initializer`, but at that point the logic seems redundant.
Since the registry must be initialized by the owner, this PR also updates the off-chain `initializeChugSplash` function to impersonate the multisig owner on …
=> maint(ct): move managed service functions out of registry

.changeset/ninety-eels-sip.md, packages/core/src/config/parse.ts, packages/core/src/utils.ts
This makes things slightly more explicit than calling `hexDataLength`.
=> maint(ct): add `isDataHexString` helper function

packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/contracts/ChugSplashRegistry.sol, packages/contracts/contracts/Semver.sol, packages/contracts/contracts/interfaces/IChugSplashManager.sol, packages/contracts/package.json, packages/core/src/languages/solidity/predeploys.ts, packages/plugins/contracts/Stateless.sol, packages/plugins/test/ManagerUpgrade.spec.ts
Previously, it was possible for the major/minor/patch inputs to the ChugSplashRegistry's `setVersion` function to differ from the ChugSplashManager's actual Semver version. This isn't likely to happen, but it'd be nice if this was prevented on-chain.
This PR changes the registry's `addVersion` function to read the semver versions from the ChugSplashManager.To do this, I created our own `Semver` contract, which is the same as Optimism's except our `Semver.version()` function returns a `Version` struct instead of a string. This `Version` struct is used in the registry's `addVersion` function to determine the keys of the `versions` mapping.
This PR also adds a `VersionAdded` event to the `addVersion` function.
=> maint(ct): check the manager's semver version in the registry's  function

packages/core/src/config/parse.ts, packages/demo/chugsplash/hello-chugsplash.ts
We previously prompted the user to confirm an upgrade even if a validation error was about to be thrown. This PR fixes that issue by putting the confirmation logic after we check for any validation errors.
=> maint(core): confirm upgrade after checking for validation errors

packages/contracts/contracts/ChugSplashManager.sol, packages/core/src/actions/bundle.ts, packages/demo/chugsplash/hello-chugsplash.ts
Previously, non-proxied contracts were included in the target bundle, which is the bundle used in the `initiateExecution` and `completeExecution` functions to initialize/finalize each proxy. It's pointless to include non-proxied contracts in these functions, and doing so would actually complicate these functions because non-proxied contracts don't have adapters.
=> maint(ct): remove non-proxied contracts from target bundles

.changeset/heavy-parrots-swim.md, packages/contracts/contracts/ChugSplashManager.sol
Previously, `adapter.initiateExecution` was inside `ChugSplashManager.executeActions` instead of `ChugSplashManager.initiateBundleExecution`.
=> fix(ct): move `adapter.initiateExecution` into the proper ChugSplashManager function

.changeset/healthy-dodos-help.md, packages/contracts/contracts/ChugSplashManager.sol
This is a cautionary measure since both functions have an external call to the `adapter`.
=> fix(ct): add reentrancy guards to the bundle initiation and completion functions

packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/contracts/DefaultGasPriceCalculator.sol, packages/contracts/contracts/interfaces/IGasPriceCalculator.sol, packages/contracts/src/constants.ts, packages/contracts/src/ifaces.ts, packages/core/src/constants.ts, packages/core/src/languages/solidity/predeploys.ts, packages/core/src/tasks/index.ts, packages/plugins/test/foundry/ChugSplash.t.sol
Many chains calculate gas in different ways, so this PR moves the gas price calculation into a separate contract from the ChugSplashManager.
=> maint(ct): move gas price calculation into modular contract

.changeset/tricky-cameras-know.md, packages/contracts/contracts/ChugSplashManager.sol
Previously, we didn't incorporate the gas used by the calldata into the estimated `gasUsed` value during remote execution in the ChugSplashManager. This caused the executor to lose money on large transactions (particularly transactions that have a large number of `SetStorage` actions).
This PR improves the `estGasUsed` calculation in the ChugSplashManager so that it's never lower than the transaction's actual `gasUsed`. I verified this by comparing the actual vs estimated gas cost of all the actions run by calling `yarn test:hardhat`, and also by deploying the demo package contract.
=> fix(ct): improve gas estimation on-chain

.changeset/empty-weeks-float.md, packages/core/src/languages/solidity/predeploys.ts, packages/executor/src/index.ts, packages/plugins/src/foundry/index.ts, packages/plugins/src/hardhat/tasks.ts
Prevents users from accidentally deploying ChugSplash on unsupported networks. ChugSplash will only be deployed automatically on local networks. If a user attempts to run ChugSplash on a live network where the contracts have not been deployed, we output an error stating that the network is not currently supported. 
Also fixes a bug where attempting to deploy ChugSplash against a network where it has already been deployed fails due to the `addVersion` step.
=> feat(pg): Only initialize ChugSplash on local networks

.changeset/nasty-clouds-wonder.md, packages/contracts/contracts/ChugSplashManager.sol, packages/core/src/utils.ts
Previously, it was possible for a low balance of ETH in the ChugSplashManager to prevent an executor from withdrawing any of their debt. This PR fixes this issue by allowing the executor to specify an amount to withdraw (as long as it's below the debt owed to them).
This PR also shortens some error strings in the ChugSplashManager to get it under the contract size limit.
=> fix(ct): allow executor to specify amount of debt to withdraw

.changeset/cool-donkeys-pull.md, packages/core/src/config/parse.ts, packages/core/src/languages/solidity/iterator.ts, packages/core/src/languages/solidity/storage.ts, packages/plugins/chugsplash/VariableValidation.config.ts, packages/plugins/contracts/Storage.sol, packages/plugins/contracts/VariableValidation.sol, packages/plugins/test/Validation.spec.ts
Allows the user to define function types in their contracts:
- Function values cannot be defined in the config, if they are then a validation error is thrown
- During encoding, we explicitly zero out the slot key of any function types
=> feat(core): Allow function types in contracts

.changeset/soft-lies-pay.md, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/contracts/ChugSplashRegistry.sol, packages/contracts/contracts/DefaultCreate2.sol, packages/contracts/contracts/interfaces/ICreate2.sol, packages/contracts/src/constants.ts, packages/contracts/src/ifaces.ts, packages/core/src/constants.ts, packages/core/src/languages/solidity/predeploys.ts, packages/plugins/test/foundry/ChugSplash.t.sol
This allows us to support non-standard Create2 formulas used by networks like ZK Sync.
Also includes some changes to fit the ChugSplashManager under the contract size limit.
=> fix(ct): use general create2 contract

packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/contracts/ChugSplashManagerProxy.sol, packages/core/src/actions/bundle.ts, packages/core/src/actions/execute.ts
This PR:
* Makes a couple minor nitpicky changes to the contracts
* Refactors the Merkle tree generation logic used by the target and action bundles
* Batches `DeployContract` and `SetStorage` actions to be executed together
=> refactor(ct,core): clean up contracts, merkle tree generation, and execution logic

.changeset/perfect-pandas-add.md, packages/core/src/actions/artifacts.ts, packages/core/src/actions/bundle.ts, packages/core/src/config/parse.ts, packages/core/src/languages/solidity/types.ts
Previously, we were using the `storageLayout` object in our codebase without taking into consideration that it may be undefined when using Foundry. This PR fixes that issue by using `getStorageLayout` throughout our codebase.
=> fix(core): ensure storageLayout object is never undefined

packages/core/src/languages/solidity/storage.ts
It appears that this error is unnecessary since we validate the inplace bytes type in `parseBytes`. Also, I believe we don't allow byte arrays, so the error is checking for the wrong thing anyways.
Note that this is the last error in the encoding logic that isn't a "this should never happen in any case" error.
=> maint(core): remove unnecessary encoding inplace bytes error

packages/core/src/languages/solidity/predeploys.ts, packages/core/src/utils.ts, packages/executor/.gitignore, packages/executor/chugsplash/ExecutorTest.config.ts, packages/executor/contracts/ExecutorTest.sol, packages/executor/hardhat.config.ts, packages/executor/package.json, packages/executor/src/index.ts, packages/executor/test/Executor.test.ts, packages/plugins/package.json, packages/plugins/src/utils.ts, yarn.lock
- Adds a basic automated test of the remote executor
- Fixes a bug where withdrawing executor payment causes the executor to crash 
- Fixes issue where executors aren't assigned roles during the `initializeChugSplash` function. I resolved this by impersonating the multi-sig and assigning the executors the roles, but we'll need to deal with this on live networks separately.
- Run `yarn test` in the executor package
- Runs automatically in our CI process
=> maint(exec): Add automated testing of remote executor

packages/core/src/actions/artifacts.ts, packages/core/src/actions/bundle.ts, packages/core/src/etherscan.ts, packages/core/src/execution/index.ts, packages/core/src/fund.ts, packages/core/src/languages/solidity/predeploys.ts, packages/core/src/tasks/index.ts, packages/core/src/utils.ts, packages/executor/src/index.ts, packages/executor/src/utils/execute.ts
Improves our off-chain gas cost estimation logic
- Only includes the cost of deploying a proxy if a proxy has not yet been deployed
- Does not include the cost of deploying any implementation contracts that have already been deployed
- Adds a fixed buffer of 150k to account for the initiate and complete function calls
Tested using the remote executor with various cases including Rabbitholes contracts and a bunch of our test configs from the plugins package.
=> fix(core): Improve gas estimation logic

.changeset/hot-lies-walk.md, packages/core/src/config/parse.ts, packages/core/src/constants.ts, packages/core/src/fund.ts, packages/core/src/languages/solidity/types.ts, packages/core/src/utils.ts
Also changes the estimate of an initiation + completion call from 100k to 200k. This is based on the cost of initiating the contract in the demo package without deploying the default proxy. This cost 100k, so the cost of initiating and completing a contract is 200k assuming that the completion tx costs the same as the initiation tx.
=> fix(ct): assert contracts are below the contract size limit

.changeset/sharp-rats-protect.md, packages/core/src/config/parse.ts, packages/core/src/fund.ts
This PR adds an assertion that checks if a bundle is too large to be executed. This is determined by estimating the gas used during the initiation txn, which is the limiting factor in this situation, because it must occur in a single transaction, unlike `executeActions`.
=> fix(core): assert valid bundle size

packages/core/hardhat.config.ts, packages/core/scripts/deploy.ts, packages/core/src/addresses.ts, packages/core/src/etherscan.ts, packages/executor/src/index.ts
Updates Etherscan verification logic for the main ChugSplash contracts. 
Note: This does not include logic for verifying default proxies. I've created a [separate ticket](https://linear.app/chugsplash/issue/CHU-221/verify-default-proxies-on-etherscan) for that b/c I believe it's a bit more involved than just verifying `Proxy.sol`.
=> maint(core): Update system Etherscan verification logic

.changeset/khaki-bees-leave.md, packages/core/src/config/parse.ts, packages/core/src/languages/solidity/predeploys.ts, packages/core/src/utils.ts
This PR extends #648 to assert that the block gas limit is > 15M in the parsing logic. I've included this because live networks may change their block gas limit over time. For example, [ZK Sync's is 2^32 - 1](https://era.zksync.io/docs/dev/developer-guides/transactions/blocks.html#block-properties), but they plan to change it in the relatively near future.
=> fix(core): assert block gas limit is sufficiently high in parsing logic

docs/how-chugsplash-works.md, packages/contracts/contracts/ChugSplashDataTypes.sol, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/test/MockChugSplashManager.sol, packages/core/src/actions/bundle.ts, packages/core/src/actions/execute.ts, packages/core/src/actions/types.ts, packages/core/src/config/fetch.ts, packages/core/src/config/parse.ts, packages/core/src/execution/index.ts, packages/core/src/fund.ts, packages/core/src/tasks/index.ts, packages/core/src/utils.ts, packages/executor/src/gql/index.ts, packages/executor/src/index.ts, packages/executor/src/utils/execute.ts, packages/plugins/src/hardhat/tasks.ts, specs/chugsplash-manager.md
Throughout our codebase, the term "bundle" currently describes two things:
1. A static data type that contains the Merkle root, its leafs, and proofs. I.e. the action bundle and the target bundle.
2. A deployment/upgrade. I.e. the bundle state, bundle status, bundle ID.
Using "bundle" as a catch-all term was more acceptable when a deployment/upgrade was basically just a single bundle. (See [here](https://github.com/chugsplash/chugsplash/blob/3a7b19cd4b6ec5556dc48d3a9f7b25de983ea713/packages/contracts/contracts/ChugSplashManager.sol#L156) for a very early version of the propose function). However, now that we use two bundles, it makes more sense to call it a "bundles ID", "bundles state", etc, but that's grammatically awkward.
In this PR, I changed all instances of case 2 to "deployment" …
=> maint: rename bundle to deployment in certain contexts

.changeset/eight-eggs-cover.md, docs/how-chugsplash-works.md, packages/contracts/.solhint.json, packages/contracts/contracts/ChugSplashDataTypes.sol, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/contracts/adapters/DefaultAdapter.sol, packages/contracts/contracts/adapters/OZTransparentAdapter.sol, packages/contracts/contracts/adapters/OZUUPSBaseAdapter.sol, packages/contracts/contracts/interfaces/IProxyAdapter.sol, packages/contracts/hardhat.config.ts, packages/core/src/actions/bundle.ts, packages/core/src/actions/execute.ts, packages/core/src/actions/types.ts, packages/core/src/config/fetch.ts, packages/core/src/config/parse.ts, packages/core/src/execution/index.ts, packages/core/src/tasks/index.ts, packages/core/src/utils.ts, packages/executor/chugsplash/ExecutorTest.config.ts, packages/executor/contracts/ExecutorTest.sol, packages/executor/src/utils/execute.ts, packages/executor/test/Executor.test.ts, packages/plugins/chugsplash/VariableValidation.config.ts, packages/plugins/contracts/Reverter.sol, packages/plugins/test/Validation.spec.ts, specs/chugsplash-manager.md
This PR also:
* Replaces revert strings with custom errors in the ChugSplashManager. This allows the contract to fit comfortably under the max contract size limit.
* Adds parsing logic that checks if any constructors revert via `estimateGas`. It displays the constructor error messages to the user for each contract in the config that would revert if deployed.
* Adds logic to the remote executor that checks if any constructors revert, again using `estimateGas`. This occurs before the executor attempts to claim the bundle. If a constructor in the config reverts, the executor calls `logger.error` and discards the execution event. (This logic is why there's no unit test for the remote executor when it handles a constructor reverting on-chain. It'd be challenging to come up with a unit test …
=> fix(ct): deploy contracts before modifying proxies during execution

package.json, packages/contracts/contracts/ChugSplashManager.sol, packages/contracts/contracts/Import.sol, packages/contracts/contracts/ManagedService.sol, packages/contracts/foundry.toml, packages/contracts/hardhat.config.ts, packages/contracts/package.json, packages/contracts/src/constants.ts, packages/contracts/src/ifaces.ts, packages/core/package.json, packages/core/src/addresses.ts, packages/core/src/languages/solidity/predeploys.ts, packages/core/src/metatxs.ts, packages/core/src/tasks/index.ts, packages/plugins/.env.example, packages/plugins/chugsplash/Metatx.config.ts, packages/plugins/test/Metatx.spec.ts, yarn.lock
Adds support for gasless proposals using meta transactions. Note that this includes an automated test that requires the use of IPFS credentials. 
You must add the following environment variable and value to your plugin's `.env` file for the new test to work. Note this is just b/c we check for the API key to determine if a gasless proposal should be done or not. The value of the key doesn't matter right now. 
`CHUGSPLASH_API_KEY=testing`
=> feat(core): Support gasless proposals with meta transactions

.changeset/twelve-rice-explain.md, packages/core/config/goerli.ts, packages/core/src/addresses.ts, packages/core/src/etherscan.ts, packages/core/src/languages/solidity/predeploys.ts, packages/core/src/utils.ts, packages/executor/src/index.ts, packages/executor/src/utils/execute.ts
Fixes a variety of bugs caught during manual integration testing of the website.
- Fixes an issue where filtering for events results in duplicate events for some node providers depending on how they handle block number filtering. 
- Fixes an edge case where fetching the previous config from IPFS for the storage slot checker fails if the previous deployment did not include any set state actions.
- Fixes an issue where linking the default proxy to its implementation on Etherscan sometimes fails due to the default proxy not being verified.
- Adds steps to deploy and verify reference DefaultProxy and ChugSplashManagerProxy contracts so that contracts deployed by our factories will be automatically verified. 
- Adds logic to catch and retry Etherscan verification failures which sometimes occur …
=> fix(exec): Fix live network specific bugs

.changeset/six-ghosts-kick.md, packages/contracts/contracts/ChugSplashManager.sol, packages/core/src/actions/bundle.ts, packages/core/src/config/parse.ts, packages/core/src/config/types.ts, packages/core/src/etherscan.ts, packages/core/src/tasks/index.ts, packages/core/src/utils.ts, packages/plugins/package.json, packages/plugins/src/foundry/index.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/test/Create3.spec.ts, packages/plugins/test/Validation.spec.ts
When deploying a proxy's implementation via Create3, we now use a salt equal to `hash(creationCodeWithConstructorArgs)`. This essentially turns Create3 into Create2 for proxy implementations.
When deploying a non-proxy contract, we log a warning instead of an error when the contract at the Create3 address has a `hash(creationCodeWithConstructorArgs)` equal to the non-proxy contract in the config.
=> fix(core): fix behavior of create3 deployments

packages/core/src/tasks/index.ts
Moves the logic for determining if the relayer should be used outside the `proposeChugSplashDeployment` since it is also used by the local deployment process.
=> fix(core): Determine usage of relay outside the proposeChugSplashDeployment function

packages/core/src/tasks/index.ts, packages/executor/test/Executor.test.ts
Removes the complex logic for determining if we should use the relayer in the propose task or not, instead we just throw an error if the API key is not defined.
=> fix(core): Error if no API key is defined when proposing

.changeset/slimy-humans-sniff.md, packages/plugins/src/hardhat/tasks.ts
The `silent` field conflicts with another Hardhat plugin in Optimism's monorepo, so I'm changing it to `hide`.
=> fix(pg): change hardhat `node` task param from `silent` to `hide`

packages/core/src/actions/artifacts.ts, packages/core/src/actions/bundle.ts, packages/core/src/config/parse.ts, packages/core/src/execution/index.ts, packages/core/src/languages/solidity/types.ts, packages/core/src/tasks/index.ts, packages/core/src/utils.ts, packages/executor/test/Executor.test.ts, packages/plugins/src/foundry/index.ts, packages/plugins/src/foundry/utils/index.ts, packages/plugins/src/hardhat/artifacts.ts, packages/plugins/src/hardhat/deployments.ts, packages/plugins/src/hardhat/tasks.ts, packages/plugins/src/scripts/display-bundle-info.ts, packages/plugins/test/Metatx.spec.ts, packages/plugins/test/Transfer.spec.ts, packages/plugins/test/Validation.spec.ts
This removes a lot of unnecessary file I/O, which should speed things up a bit. Using a single persistent object for the artifacts also makes it easy to modify the build info objects, which is necessary while [this Foundry bug](https://github.com/foundry-rs/foundry/issues/4981) is pending.
=> maint(core): remove `ArtifactPaths` in favor of `ConfigArtifacts`

packages/plugins/foundry-contracts/ChugSplash.sol, packages/plugins/src/foundry/index.ts
Fixes an issue where the chugsplash manager address was not properly computed in foundry. This was due to two issues: 
1. The bytecode of the proxy was fetched using `type(ChugSplashManagerProxy).creationCode` which cannot be used for computing addresses b/c the bytecode is dependent on the users compiler configuration. I've updated this to instead use FFI to fetch the exact bytecode from the artifact like we do for the rest of our create2 deployments in foundry. 
2. The constructor args were incorrectly appended to the bytecode. The constructor args need to be separately encoded before they are appended to the bytecode using encodePacked.
=> fix chugsplash manager computed address incorrect

packages/core/src/languages/solidity/predeploys.ts, packages/core/src/utils.ts, packages/plugins/.gitignore, packages/plugins/foundry-contracts/ChugSplash.sol, packages/plugins/src/foundry/index.ts, packages/plugins/src/scripts/ChugSplash.s.sol, yarn.lock
- Fixes a few bugs when deploying the core contracts against Anvil
- Calls `ffiDeployOnAnvil` in the ChugSplash library constructor
- Specifies a custom gas limit for transactions sent from the ChugSplash library
- Removes the call to `ensureChugSplashInitialized` from the deploy function b/c it does not work when broadcasting yet. For the time being, we will have to call it from outside the broadcast. Since it requires the rpcurl, this means it must be called from the deployment script. See the `src/scripts/ChugSplash.s.sol` for an example. This will be resolved when the raw transaction cheatcode is released.
=> Fix incorrect gas limit when broadcasting

packages/core/src/constants.ts, packages/core/src/messages/index.ts, packages/core/src/tasks/index.ts, packages/core/src/utils.ts, packages/plugins/foundry-contracts/ChugSplash.sol, packages/plugins/src/cli/Propose.s.sol, packages/plugins/src/cli/index.ts, packages/plugins/src/foundry/get-bundle-info.ts, packages/plugins/src/foundry/index.ts, packages/plugins/src/foundry/logs.ts, packages/plugins/src/foundry/utils/index.ts, packages/plugins/src/hardhat/tasks.ts, packages/plugins/src/sample-project/index.ts, packages/plugins/src/scripts/ChugSplash.s.sol
This PR:
* Updates the `propose` function in Solidity to support TypeScript configs as well as clean error messages, which are implemented the same way as `getBundleInfo`.
* Various improvements to: `npx chugsplash init`
* Retrieves the user's contract, test, and script file names via `execAsync(forge config --json)`.
* Supports TypeScript and JavaScript ChugSplash configs
* Improves the `chugsplash init --help` flag
* Improvements to `npx chugsplash propose`
* Uses an `--rpc-url` flag instead of `--network` since this is what `forge script` does
* Displays helpful error messages to the user
* Improves the `--help` flag
* Removes the `claim` and `listProjects` from the Hardhat CLI tasks
=> Random cleanup

packages/core/src/config/parse.ts, packages/executor/chugsplash/ExecutorTest.config.ts, packages/plugins/chugsplash/VariableValidation.config.ts
Sets the value of `unsafeAllow.flexibleConstructor` to false. This is a simple way to do it, for now, later we can come back and we'll have an easy spot to add in more complex logic for determining the value based on the type of contract or some other criteria.
=> Default unsafeAllow.flexibleConstructor to false

packages/core/src/tasks/index.ts, packages/core/src/types.ts, packages/plugins/contracts/foundry/ChugSplash.sol, packages/plugins/contracts/foundry/Propose.sol, packages/plugins/script/ChugSplash.s.sol, packages/plugins/src/cli/index.ts, packages/plugins/src/foundry/index.ts, packages/plugins/test/Metatx.spec.ts, yarn.lock
- Fixes an issue where proposal would not exit early if there is nothing to deploy
- Fixes an issue where errors caught during proposals were not properly output
- Fixes an issue where proposal success messages do not accurately reflect the outcome (i.e successful b/c a deployment was actually proposed, or successful b/c there were no changes since the last deployment)
Does not fix a related issue with the deploy function where the success message also does not accurately reflect the actual outcome of the deployment. If you deploy a config with a single immutable contract and then attempt to deploy that same config again, it will succeed with the same message both times: 
```
== Logs ==
Success!
Stateless: <address>
```
But the underlying behavior is different. The first time the contract …
=> Fix Proposal Bugs

packages/core/src/tasks/index.ts
Fixes an issue where the post-deploy actions fail when run against a live network due to the unhandled use of the `hardhat_metadata` rpc method.
=> fix(core): Handle error thrown when using hardhat_metadata on a live network

.changeset/itchy-kings-brush.md, packages/plugins/src/cli/index.ts
Fixes an issue where we fail to properly read the registry code when proposing against a live network.
=> fix(pg): Fix issue where reading registry code fails on live network during proposal

.changeset/breezy-actors-report.md, .changeset/perfect-queens-wonder.md, docs/foundry/getting-started.md, packages/contracts/package.json, packages/plugins/contracts/foundry/ChugSplash.sol, packages/plugins/contracts/foundry/ChugSplashConstants.sol, packages/plugins/contracts/foundry/ChugSplashPluginTypes.sol, packages/plugins/contracts/foundry/ChugSplashUtils.sol, packages/plugins/contracts/foundry/Propose.sol, packages/plugins/package.json, packages/plugins/script/write-constants.ts
Fixes some issues with the production installation: 
- The contracts package doesn't actually include the contracts themselves, but our plugin relies on importing them
- The plugins contracts require version 0.8.15 but this can cause conflicts in the users repo depending on the version they install. For some reason, having mismatching versions was not an issue within our repo but it is a problem when the package is installed in a users project. I fixed this by replicating foundries pattern of using a wide version range. 
- Removes import of the bedrock Proxy.sol contract from the ChugSplash library since it requires specifically version 0.8.15 which will cause issues as well. 
- Removes some extra files from the plugins package which aren're required in the prod package. 
- Updates the …
=> fix(pg): Fix issues with production package installation

.changeset/weak-donkeys-cheer.md, packages/plugins/src/foundry/get-bundle-info.ts, packages/plugins/src/foundry/index.ts, packages/plugins/src/foundry/options.ts, packages/plugins/src/foundry/utils/index.ts
Uses a cache to fetch the correct build info files for each contract source name to avoid reading all of the build info files.
I investigated a separate issue where we require that contracts be located in a file that matches their exact name. This is an issue with fetching the correct contract artifact and not the build info. I believe that this caching scheme would actually work fine for contracts in files with different names. We'll have to test it and see when we address that issue. I determined it to be outside the scope of this specific PR.
=> fix(pg): Use cache to avoid reading all build info files

.changeset/tough-spiders-roll.md, packages/plugins/src/foundry/utils/index.ts
Fixes an edge case where there can be some ambiguity in which contract artifact is being used if there are multiple contracts in different files with the same name. We handle this by tracking which contract names appear in different source files, and then throwing an error if the user references a contract that appears in multiple files without using the fully qualified name.
=> fix(pg): Detect ambiguous contract names in configs when using foundry

.changeset/hip-queens-brush.md, packages/core/src/utils.ts
Fixes an issue where the `getGasPriceOverrides` function returns a gas price that causes transactions to hang on polygon mainnet. This is due to an underlying bug in how Ethers interacts with Polygons implementation of EIP-1559. This issue has been natively resolved in Ethers v6, but migrating to the new Ethers version is non trivial so I've [implemented a simple workaround](https://github.com/ethers-io/ethers.js/issues/2828#issuecomment-1603383487). However, we should migrate to Ethers v6 when we have time for it as this workaround does not fully resolve the issue. This workaround simply makes it possible to send transactions on polygon using Ethers, but it's somewhat unreliable (I had to restart the core contract deployment process 3 times before it fully completed).
=> fix(core): Resolve bug sending transactions on polygon mainnet

README.md
The URLs for "contributing guide" and "good first issues" are broken and return 404. This PR addresses this and other inconsequential markdown linting warnings such as using "-" instead of "*" for unordered lists.
I believe like me, every other person would look at the README on first contact with the repo. Therefore, the error is obvious if they were to try reading through the `CONTRIBUTING.md` file through the README.
=> Readme link error

.changeset/slimy-buttons-love.md, docs/ci-foundry-proposals.md, docs/ci-hardhat-proposals.md, docs/ops-foundry-getting-started.md, docs/ops-hardhat-getting-started.md, packages/core/src/tasks/index.ts
Fixes an issue where the proposal task throws an error if you attempt to propose when nothing has changed since the last deployment. This is an issue because if we throw an error here then it causes problems when using us in CI. The correct behavior is to simply do nothing and log that nothing is happening. This allows the CI check to succeed in this case.
=> fix(core): fix proposal failure when nothing has changed

.changeset/rare-sloths-invent.md, packages/core/src/tasks/index.ts
Fixes an issue where removing some data from your config file can result in our DB containing a slightly out-of-date canonical config which can result in bugged deployments. 
For example prior to this PR, if I deployed with this config: 
```
const config: UserConfigWithOptions = {
projectName: 'Foundry Deployment',
options: {
orgId: <ORG_ID>,
owners: [<OWNER>],
ownerThreshold: 1,
testnets: ['arbitrum-goerli'],
mainnets: [],
proposers: [<PROPOSER>],
},
contracts: ...
}
```
And then I deployed with this config: 
```
const config: UserConfigWithOptions = {
projectName: 'Foundry Deployment',
options: {
orgId: <ORG_ID>,
owners: [<OWNER>],
ownerThreshold: 1,
testnets: ['optimism-goerli'],
mainnets: [],
proposers: [<PROPOSER>],
},
contracts: ...
}
```
The canonical config in the DB would contain …
=> fix(core): Combine previous canonical config with new config

.changeset/warm-spiders-reply.md, packages/plugins/package.json, yarn.lock
The latest version of the `@swc/core` dependency is incompatible with `ts-node`, so we restrict the version of the former to `1.3.75`.
=> fix(pg): restrict @swc/core dependency version

packages/contracts/test/mocha/merkle-tree.spec.ts
- Fixes an [issue where the check for Merkle tree invariant 5 in `merkle-tree.spec.ts` was incomplete](https://discord.com/channels/883432404780466176/1176261963106492526/1177463360426618962).
=> fix(mt): Merkle tree generation invariant five test incomplete

.changeset/small-seas-arrive.md, .gitignore, docs/cli-existing-project.md, docs/writing-scripts.md, packages/plugins/contracts/foundry/Sphinx.sol, packages/plugins/contracts/test/script/Cases.s.sol, packages/plugins/contracts/test/script/Empty.s.sol, packages/plugins/contracts/test/script/Large.s.sol, packages/plugins/contracts/test/script/PartiallyEmpty.s.sol, packages/plugins/contracts/test/script/RevertDuringSimulation.s.sol, packages/plugins/contracts/test/script/Simple.s.sol, packages/plugins/script/Sample.s.sol, packages/plugins/src/sample-project/sample-contracts.ts
Before this PR, the user's `run` function needed to include the `override` keyword. After this PR, this keyword is no longer included.
We should make this change now because it's a breaking change that's necessary to allow the user to use function names other than `run()` in their script, which we plan to support in the future. It's a breaking change because the Solidity compiler will throw this error if the user attempts to override a function that doesn't exist: `Error (7792): Function has override specified but does not override anything.`
=> fix(pg): stop requiring the user to override the `run()` function in their script

.changeset/slimy-toes-taste.md, packages/core/src/utils.ts, packages/plugins/script/Sample.s.sol
Adds an environment variable `SPHINX_INTERNAL__DISABLE_GAS_PRICE_OVERRIDES` which allows disabling the gas price overrides function.
=> feat(core): Allow disabling gas price overrides

.changeset/eleven-gorillas-destroy.md, packages/demo/test/Solc.spec.ts, packages/plugins/src/cli/deploy.ts, packages/plugins/src/cli/propose/index.ts, packages/plugins/src/foundry/utils/index.ts, packages/plugins/test/mocha/cli/deploy.spec.ts, packages/plugins/test/mocha/cli/propose.spec.ts
Before this PR, the Deploy and Propose CLI commands force re-compiled the user's contracts at the beginning of the command. The problem is that it's common to spend a significant amount of time waiting for re-compilation to occur then run into an error thrown at some point later in the command. For example, this scenario can occur if an error is thrown in the user's script during the transaction collection phase. When this occurs, the user must then sit and wait for re-compilation to occur all over again. If this process repeats multiple times, it becomes quite frustrating to use our plugin.
This PR fixes the issue by force-recompiling as late as possible in these commands. Specifically, we force recompile before calling `getConfigArtifacts`. This PR also moves a bit of logic earlier in …
=> perf(pg): compile as late as possible in CLI commands

.changeset/kind-pans-train.md, packages/core/src/networks.ts, packages/core/src/utils.ts, packages/plugins/src/hardhat/simulate.ts, packages/plugins/test/mocha/common.ts, packages/plugins/test/mocha/simulate.spec.ts
This PR resolves a bug that was occurring on Anvil nodes that fork live networks. The bug was caused by the fact that we were fast forwarding the block number on these networks, which was causing network timeouts. Now, we only fast forward on non-forked local nodes (i.e. nodes that begin with an entirely fresh state).
=> fix(pg): remove logic that fast forwards block number on forked local nodes

.changeset/stupid-mugs-exercise.md, packages/plugins/src/hardhat/hardhatRunner.ts, packages/plugins/src/hardhat/simulate.ts
Previously, if the simulation threw an error, any warnings from the simulation were also displayed in the error message. It wasn't possible to distinguish between a warning and the error that caused the simulation to fail, which made it difficult to understand why the error occurred. This PR fixes this issue by only displaying the error message that caused the simulation to fail.
=> fix(pg): display error from child process in simulation

.changeset/modern-lies-design.md, packages/demo/test/init.spec.ts, packages/plugins/src/sample-project/sample-contracts.ts
This PR fixes the quickstart guide, which broke because it attempted to deploy the sample contract to the same address for everybody.
=> fix(pg): use `CREATE2` salt in quickstart guide to prevent contract address collision

.circleci/config.yml
Disables the contract tests if the branch is not `develop`. This means the contracts tests will run if you open a PR where the *source* branch is `develop` regardless of what the target branch is. Typically, this would be `master`, so this change is effectively disabling the contracts tests unless we are merging to main. 
I did it this way because CircleCI doesn't expose a nice interface for checking the target branch of a PR. We could do it by checking the target branch, but we'd have to use the GitHub CLI to do that, which seems overly complicated to me.
=> maint(ci): Only run contract tests when branch is develop

.changeset/old-ladybugs-cross.md, packages/core/package.json, packages/core/src/utils.ts, packages/core/test/utils.spec.ts
Fixes an issue where the following line was displayed to the user if they aren't in a git repository:
> "fatal: not a git repository (or any of the parent directories): .git".
I manually checked that there this error message isn't displayed in a repo that doesn't have git
=> fix(core): discard git message when user is not in a git repository

.changeset/slimy-impalas-move.md, packages/core/src/utils.ts
Sets the gas price to 10x the recommended value on linea goerli to [workaround this bug](https://github.com/ethers-io/ethers.js/issues/4533).
=> fix(pg): Resolve linea transaction hang

.github/workflows/release.yml
Removes a release workflow step that is not actually necessary. It was added to generate a tag which we would use to install the library using `forge install`, but we're using commit hashes instead of tags so it is not necessary.
=> fix(ci): Remove extra tag release step

.changeset/quiet-buses-provide.md, packages/contracts/scripts/write-constants.ts
Fixes an issue where the constants generation script wasn't using the latest commit hash.
=> fix(ci): Fix constants generation script

.changeset/weak-readers-admire.md, .circleci/config.yml, packages/plugins/src/cli/install/index.ts, packages/plugins/src/cli/setup.ts, packages/plugins/src/sample-project/index.ts
Updates the `sphinx install` command to handle cases where an old version of the Sphinx library was installed by removing it before then installing the required version.
I replicated this issue with the following steps:
1. Run through the quickstart with the currently released packages
2. Create a new branch in the sphinx repo `v0.18.0-test` (or any name that does not include `@`)
3. Push the branch to github
4. Run `forge install sphinx-labs/sphinx@v0.18.0-test`
Note that this issue only occurs if the branch you want to install was not on GitHub when you first installed the sphinx library during the quickstart. I tested this fix quite extensively and confirmed the `install` command works in the following scenarios in addition to resolving the bug itself:
- the library is not installed at …
=> fix(pg): Handle prior installation of sphinx library contracts

.changeset/curvy-nails-end.md, .circleci/config.yml, packages/core/src/tasks/index.ts, packages/core/src/utils.ts
Previously, we were combining contract sources from different build info files as long as the build info files had the same `solcLongVersion`. This was problematic because different build info files can contain different compiler settings. This PR fixes this issue by only combining sources from the _same_ build info file. We identify each build info file according to its `id` field.
I manually tested that this fixes the issue in the "Steps to reproduce" section of the [ticket for this issue](https://linear.app/chugsplash/issue/CHU-445/fix-code-in-the-plugin-that-creates-the-sphinxinputs-array).
=> fix(core): merge compiler inputs based on build info ID instead of solc version

.changeset/empty-beers-breathe.md, ops/ci-builder/Dockerfile
The new `forge-std` version contains the `AccountAccess` structs, which are used in the state diff.
=> chore(deps): bump forge-std and use Sphinx fork of Foundry

docs/cli-existing-project.md
I checked that there's only one instance of this mistake in the monorepo (including user-facing docs and TypeScript logic)
=> docs: fix npm sphinx installation command

.circleci/config.yml
Adds back in the `git reset --hard` step, but this time the step failing will not cause the whole CI process to fail.
=> fix(ci): Reset in ci and handle failure

packages/contracts/contracts/foundry/Sphinx.sol, packages/contracts/contracts/foundry/SphinxPluginTypes.sol, packages/contracts/contracts/foundry/SphinxUtils.sol, packages/contracts/test/SphinxUtils.t.sol, packages/demo/foundry.toml, packages/plugins/src/cli/deploy.ts, packages/plugins/src/cli/propose/index.ts, packages/plugins/src/foundry/decode.ts
Removes the "max depth exceeded" error described in the [previous PR](https://github.com/sphinx-labs/sphinx/pull/1415), which was happening when ABI decoding a large `DeploymentInfo` object. Now, we serialize the `DeploymentInfo` struct to JSON in Solidity instead of ABI encoding it.
This PR uses the `vm.serialize*` cheatcodes extensively, which are pretty unintuitive IMO. Here's a brief overview of the cheatcodes, which should hopefully save you some time.
Each `vm.serialize` cheatcode is in the format `vm.serialize(<object_key>, <value_key>, <value>)`.
* `<object_key>`: An arbitrary string that Foundry uses internally to store the JSON in memory. This key is *not* part of the actual JSON.
* `<value_key>`: An arbitary string, which is an actual key in the JSON.
* `<value>`: The value of …
=> fix(pg): resolve 'max depth exceeded' error for large deployments

packages/core/src/config/types.ts, packages/core/src/tasks/index.ts, packages/core/src/utils.ts
Adds a version number to the compiler config which is supplied to the website when the config is pinned. 
I’m adding logic to the website to ensure that we never accidentally attempt execute a compiler config which is not compatible with the current version of the executor. 
I also decided to make this release backwards compatible. We can do this by running two versions of the executor, one of the current version of the plugin, and one for the updated version. I decided to do this because Mean finance is currently in the process of doing some deployments using the old format and I would like those to go smoothly. I think this is the best way to do that. Once Mean Finance is done with their deployments, we will drop support for the old compiler config version. I also think this is good …
=> feat(pg): Track compiler config major version

.changeset/nice-planets-smoke.md, packages/plugins/src/foundry/utils/index.ts, packages/plugins/test/mocha/foundry/utils.spec.ts
Catches a bug where the `findFullyQualifiedNames` function wasn't normalizing the `scriptPath` entered by the user, which prevented it from finding the corresponding fully qualified name(s) in the build info cache. This bug applied to paths starting with a period (e.g. "./path/to/file.sol") or absolute paths. This PR resolves the bug by calling `path.relative` in `findFullyQualifiedNames` to normalize the path to be in the format "path/to/file.sol", which matches the format of the fully qualified names.
=> fix(pg): handle different path formats when asserting no linked libraries

packages/core/src/config/types.ts, packages/core/src/networks.ts, packages/core/src/tasks/index.ts, packages/core/src/utils.ts
Moves the location of the `COMPILER_CONFIG_VERSION` constant so it can be imported by the website.
=> fix(core): move COMPILER_CONFIG_VERSION const location

.changeset/witty-kids-shop.md, docs/ci-proposals.md, docs/cli-existing-project.md, docs/cli-quickstart.md, packages/plugins/src/cli/install/index.ts, packages/plugins/src/cli/setup.ts
- Updates the docs to recommend using our [GitHub action](https://github.com/marketplace/actions/sphinx-foundry-toolchain) to install the Foundry fork in CI (note that this does mean other CI platforms than GitHub will not work, but I think that is an acceptable limitation for now).
- Update the `install` command to include the `ci` option that is explicitly intended to be used in CI and completely skips the installation of our fork (because the GitHub action handles this).
=> fix(pg): Recommend using github action in CI

.changeset/twelve-baboons-swim.md, packages/core/src/constants.ts, packages/plugins/src/cli/deploy.ts, packages/plugins/src/cli/propose/index.ts
Fixes the following edge case:
1. User specifies a `gas_limit` field in their `foundry.toml` ([docs](https://book.getfoundry.sh/reference/config/testing?highlight=gas_limit#gas_limit)). (xkeep3r sets it to 30M)
2. The `gas_limit` is used in the forge script that collects their transactions
3. An "out of gas" error occurs in the collection script
This didn't happen before in keep3r's integration because we used to collect the transactions in a separate Forge script from estimating the Merkle leaf gas. The 'out of gas' error occurs after estimating the Merkle leaf gas.
I manually checked that this fixes the issue in keep3r's integration
=> fix(pg): set max block gas limit in Forge script during collection

.changeset/lovely-ants-agree.md, packages/contracts/contracts/foundry/SphinxUtils.sol, packages/core/src/networks.ts, packages/core/src/utils.ts, packages/plugins/src/foundry/decode.ts, packages/plugins/src/foundry/utils/index.ts
Foundry converts strings like `projectName` to integers if the string contains all numbers. This is a [bug in Foundry](https://github.com/foundry-rs/foundry/issues/6533).
We now ABI encode all string fields in the `DeploymentInfo` object when we serialize it in Solidity. Then, in the TypeScript `decodeDeploymentInfo` function, we ABI decode the strings. We ABI encode the strings to ensure that Foundry doesn't serialize them as numbers, which could cause them to lose precision due to JavaScript's relatively low integer size limit.
Notes:
* I manually checked that every field in the `DeploymentInfo` will convert to its correct type
* Created a type predicate, `isDeploymentInfo`, to enforce that the fields are the correct type
=> fix(pg): prevent Foundry from serializing strings as numbers

.changeset/green-cups-train.md, packages/contracts/contracts/foundry/Sphinx.sol, packages/core/src/actions/execute.ts, packages/core/src/utils.ts, packages/plugins/src/foundry/decode.ts, packages/plugins/test/mocha/common.ts
Scroll's block gas limit is 10M. I didn't notice it until now because the simulation contract's gas limit was previously 2 million, and I recently bumped it to 5 million.
A contract near the max size limit was previously not executable on Scroll because of our gas heuristics.
The goal of this PR is to update our gas heuristics to allow large contracts to be deployable on Scroll. The updated heuristics allow us to comfortably deploy a contract at the max size limit with 25 SSTOREs in its constructor. (Specifically, this contract has >1.7M gas of wiggle room). However, I think it's likely that a user will eventually deploy something that's over our new size limit. I think this is most likely to happen when a contract deploys another contract in its constructor, like how our …
=> fix(core): adjust gas heuristics to support large contracts on Scroll

.changeset/clever-vans-yell.md, .changeset/hot-frogs-film.md, packages/contracts/contracts/foundry/Sphinx.sol, packages/contracts/contracts/foundry/SphinxPluginTypes.sol, packages/contracts/contracts/foundry/SphinxUtils.sol, packages/core/src/config/types.ts, packages/core/test/preview.spec.ts, packages/plugins/src/foundry/decode.ts, packages/plugins/src/hardhat/simulate.ts, packages/plugins/test/mocha/common.ts, packages/plugins/test/mocha/mock.ts
Previously, our simulation was always using the latest block, which was potentially causing it to be flaky. This PR attempts to make the simulation more reliable by using a less recent block number. Specifically, we use the same block number in the simulation and the collection phase.
An alternative approach is to use a block number that's a certain number of blocks behind the latest block number. I think it's an acceptable alternative, but less than ideal for a couple reasons:
1. Different networks have vastly different block times, so it may be tricky to choose a single number of blocks to rewind. E.g. Rootstock's block time is 33s whereas Arbitrum's seems to be multiple blocks per second.
2. Rewinding a certain number of blocks is prone to the following edge case, which is admittedly …
=> fix(pg): make simulation more reliable by using less recent block number

.changeset/eleven-cherries-vanish.md, packages/plugins/src/cli/deploy.ts, packages/plugins/src/cli/propose/index.ts
This doesn't fix any particular bug, but it decreases the chance that [this type of bug](https://github.com/sphinx-labs/sphinx/pull/1425) happens in the future. This PR is simply a preventive measure.
=> fix(pg): normalize script path

packages/core/src/actions/execute.ts, packages/core/src/artifacts.ts, packages/core/src/config/types.ts, packages/core/src/etherscan.ts, packages/core/src/tasks/index.ts, packages/plugins/src/cli/deploy.ts, packages/plugins/src/cli/propose/index.ts, packages/plugins/src/cli/types.ts, packages/plugins/src/foundry/utils/index.ts, packages/plugins/src/hardhat/simulate.ts, packages/plugins/test/mocha/common.ts, packages/plugins/test/mocha/foundry/decode.spec.ts, packages/plugins/test/mocha/foundry/utils.spec.ts, packages/plugins/test/mocha/mock.ts
Optimize the size of the DeploymentConfig by only including each build info object once.
=> fix(pg): Optimize BuildInfo storage in DeploymentConfig

.changeset/forty-hounds-yawn.md, packages/plugins/src/sample-project/index.ts
Fixes a bug where the Foundry fork is not installed during the init command.
=> fix(pg): init command does not install foundry fork

packages/core/package.json, packages/demo/package.json, packages/plugins/package.json, yarn.lock
- Moves the hardhat dependency to the top level of the monorepo since we had it listed as a dependency in a lot of places
- Bumps the hardhat version to `2.20.1`
I believe this is likely to resolve the #CHU-506, but it's hard to say for certain. I was not able to replicate that issue when linking the monorepo locally. I believe it is likely to be due to an incorrect installation of dependencies probably related to the fact that we had hardhat listed as a peer dependency in the `plugins` package which does not make sense given our current usage of it.
=> maint(pg): Bump hardhat version

.changeset/few-carpets-change.md, README.md, packages/contracts/contracts/foundry/SphinxConstants.sol, packages/contracts/src/networks.ts, packages/core/src/actions/execute.ts, packages/core/src/actions/types.ts, packages/core/src/networks.ts, packages/core/src/utils.ts, packages/core/test/convert.spec.ts, packages/plugins/src/cli/utils.ts, packages/plugins/src/foundry/utils/index.ts
- Properly calculates the gas cost in our heuristic using the call data cost of 68 per non-zero byte on Rootstock since they do not implement EIP-2028
- Standardizes the way we handle using the 80% block gas limit on Rootstock and Scroll and uses a boolean in the SPHINX_NETWORKS array to implement that
- Moves the buffer we add on the gas limit for action execution on Rootstock out of the `executeActionsViaManagedService` function and into the relayer service
- Adds support for Rootstock testnet.  I'm ok with supporting this and was able to find a functional node provider for it. I would prefer people to run into issues with the gas limit on a testnet rather than mainnet
- I also added a minor unrelated thing to this PR: A check that the user has a compatible NodeJS version installed. …
=> fix(core): Rootstock

.changeset/eight-dolls-call.md, packages/core/src/actions/execute.ts, packages/plugins/src/hardhat/hardhatRunner.ts, packages/plugins/src/hardhat/simulate.ts
Adds timeout and retry logic to the simulation mainly for the purpose of making proposals more reliable.
Note that I chose not to implement retries in the deploy CLI command as part of this PR because that is actually a pretty separate task, would have caused this to take much longer, and generally wasn't the reason we decided to prioritize this. 
I've created a [new ticket](https://linear.app/chugsplash/issue/CHU-583/add-logic-to-relayer-service-to-handle-retrying-with-a-higher-gas) specifically to cover implementing retries in the deploy CLI task.
=> feat(pg): Add timeout and retry logic to simulation

.changeset/rich-turkeys-act.md, packages/core/src/artifacts.ts, packages/core/src/utils.ts, packages/plugins/src/cli/deploy.ts, packages/plugins/test/mocha/artifacts.spec.ts, packages/plugins/test/mocha/cli/deploy.spec.ts, packages/plugins/test/mocha/common.ts, packages/plugins/test/mocha/dummy.ts, packages/plugins/test/mocha/fake.ts, packages/plugins/test/mocha/mock.ts
The changes to the artifact generation logic are simple; the vast majority of this PR is just adding dummy/fake variables for tests, and also updating the existing artifact testing logic to reflect the updated interface to the `makeDeploymentArtifacts` function
=> fix(core): keep previous deployment artifacts

.changeset/two-shoes-pull.md, .circleci/config.yml, .eslintrc.js, package.json, test/changesets.spec.ts
Adds release guard rails, so we are forced to always make a `plugins` package release at the same time that we make a
=> feat(ci): Add release version guards

docs/ci-proposals.md, docs/cli-existing-project.md, docs/cli-propose.md, docs/cli-quickstart.md, docs/configuration-options.md, docs/writing-scripts.md
Updates the docs to include arbitrary network names in proposals. Also includes configuration instructions for the `propose --networks [mainnets|testnets]` option. The next couple PRs will implement the new network UX.
=> docs: remove networks in sphinx config in favor of rpc_endpoints

.changeset/large-lemons-burn.md, packages/plugins/src/hardhat/simulate.ts
- Removes the logic to stop retries from happening if an error is due to rate limiting
- Adds logic to reset the simulation fork if a rate limit happens. See the inline comment for more information on this.
=> fix(core): Continue with retries on rate limiting

.changeset/good-fans-relax.md, packages/contracts/contracts/foundry/Sphinx.sol, packages/contracts/contracts/foundry/SphinxPluginTypes.sol, packages/contracts/contracts/foundry/SphinxUtils.sol, packages/contracts/src/networks.ts, packages/contracts/src/types.ts, packages/contracts/test/mocha/moonbeam-gas.spec.ts, packages/core/src/config/types.ts, packages/core/src/networks.ts, packages/plugins/src/foundry/decode.ts, packages/plugins/src/foundry/utils/index.ts, packages/plugins/test/mocha/artifacts.spec.ts, packages/plugins/test/mocha/common.ts
- Handle [Moonbeams' irregular method of calculating gas](https://docs.moonbeam.network/builders/get-started/eth-compare/tx-fees/) per byte of storage used. 
- Enables the `useHigherMaxGasLimit` option on Moonbeam and related networks.
Since Moonbeam has a rather low block gas limit (15 million), and the increased storage costs make it more expensive to deploy contracts, I realized we probably don't support max size limit contracts on Moonbeam or its related networks. I tested this by trying to deploy the DCAHub contract, which I couldn't deploy even with the `useHigherMaxGasLimit` option enabled. It is quite close, though, so we should be able to make it work pretty easily. 
I went ahead and enabled the `useHigherMaxGasLimit` option in this PR. I've created a [separate …
=> fix(pg): Handle higher storage cost on Moonbeam

.changeset/warm-shirts-rhyme.md, packages/plugins/src/cli/deploy.ts, packages/plugins/src/cli/propose/index.ts
Removes `FOUNDRY_SENDER` during the collection step.
=> fix(pg): Remove FOUNDRY_SENDER when collecting transactions

.changeset/itchy-hornets-marry.md, README.md, packages/contracts/src/networks.ts, packages/core/hardhat.config.ts, packages/core/src/actions/execute.ts, packages/core/src/constants.ts, packages/core/src/etherscan.ts, packages/core/src/networks.ts, packages/core/test/verification-config.spec.ts, packages/plugins/src/cli/deploy.ts, packages/plugins/src/hardhat/simulate.ts, packages/plugins/test/mocha/common.ts
- Changes the `etherscan` field in the SPHINX_NETWORKS array to support multiple block explorers
- Adds support for Blockscout on all networks where it's running
- Changes the name of some of the environment variables used for block explorer keys to clearly differentiate between etherscan and blockscout
- Adds logic to the deploy task to handle choosing the block explorer if there are multiple available. We chose etherscan if available before falling back to blockscout
=> feat(core): Smoothly handle blockexplorer outages on the website

.circleci/config.yml
Removes the use of submodules in our project including steps to handle their installation in the CI process. We can do this b/c #1530 removed the installation of `forge-std` in favor of having all of the files stored locally within the repo.
=> maint(ct): Remove submodules

.changeset/nice-guests-camp.md, packages/core/src/artifacts.ts
Updates artifact fetch request to get a pre-signed URL and then download the artifacts directly from S3. This allows for arbitrarily large artifact files and resolves [CHU-675](https://linear.app/chugsplash/issue/CHU-675/fix-the-error-that-0xbased-ran-into-when-fetching-deployment-artifacts).
=> fix(pg): Fetch artifacts via presigned url

.changeset/purple-crews-punch.md, packages/contracts/contracts/foundry/SphinxUtils.sol, packages/contracts/foundry.toml, packages/plugins/contracts/test/script/issues/CHU676.s.sol, packages/plugins/contracts/test/script/issues/Owned.sol, packages/plugins/test/mocha/cli/propose.spec.ts
Fixes an issue where calls to the SphinxUtils contract could be included in the deployment if they happened during the user script. I.e if the user called `safeAddress()`, then the call to SphinxUtils to fetch the address would have been included.
=> fix(ct): filter calls to SphinxUtils out of state diff

.changeset/famous-readers-jam.md, .circleci/config.yml, .gitmodules, packages/contracts/contracts/foundry/SphinxUtils.sol, packages/contracts/test/SphinxUtils.t.sol
Adds logic to the foundry version validation process to detect if the `depth` field is not included.
=> fix(ct): Detect missing depth field

.changeset/purple-jars-knock.md, packages/contracts/contracts/foundry/SphinxUtils.sol, packages/contracts/test/issues/CHU663/CHU663.s.sol
Resolves an infinite loop that can occur if the user calls `safeAddress()` or some other function that requires the `sphinxConfig` from within their `configureSphinx()` function.
=> fix(ct): Prevent infinite loop in configureSphinx function

.changeset/sixty-worms-agree.md, packages/plugins/src/hardhat/simulate.ts
Adds logic to detect if the hardhat config we use for the simulation is not in the expected location. This can occur if the user's package manager is configured to store dependency files in non-standard locations. I've confirmed this is not an issue with PNPM, but I believe it would be an issue with some yarn configurations (especially yarn versions 2 and 3). 
I was not able to come up with a good true solution for this which is why this PR just adds logic to throw a better error message. I believe the ideal solution is to switch to using a precompiled NodeJS binary for installation, which would not be subject to this issue.
=> fix(pg): Throw an error if the simulation is going to fail due to a missing hardhat config

.changeset/short-doors-beg.md, packages/core/src/preview.ts
A temporary solution to the bug where we fail to properly infer a contract artifact where we simply suggest running `forge build --force` if the user thinks we made a mistake.
=> fix(core): Suggest rebuilding with --force if we fail to infer a contract artifact

.changeset/long-chairs-hunt.md, packages/plugins/src/hardhat/hardhatRunner.ts
I added logic to pass through the getaddrinfo error if it occurs many times during the simulation. This PR updates that logic to follow the pattern of passing up errors using JSON objects.
=> fix(pg): Conform to standard JSON format for getaddrinfo error

.changeset/clever-turtles-applaud.md, packages/core/src/actions/execute.ts, packages/core/src/errors.ts, packages/core/src/index.ts, packages/core/src/utils.ts, packages/plugins/contracts/test/script/Simple.s.sol, packages/plugins/package.json, packages/plugins/src/cli/deploy.ts, packages/plugins/src/hardhat/simulate.ts, packages/plugins/test/mocha/cli/deploy.spec.ts, packages/plugins/test/mocha/common.ts, packages/plugins/test/mocha/dummy.ts, packages/plugins/test/mocha/fake.ts, packages/plugins/test/mocha/simulate.spec.ts
Adds logic that would have caught the error in this ticket: [Contract addresses not properly calculated for new keyword](https://linear.app/chugsplash/issue/CHU-659/contract-addresses-not-properly-calculated-for-new-keyword). Specifically, we now check that all of the contracts in the NetworkConfig have been deployed at the end of the simulation. I also updated an integration test in `deploy.spec.ts` to deploy the same project twice, which would have caused this error if we were still using `FOUNDRY_SENDER`.
Notes:
* This PR doesn't fix the `FOUNDRY_SENDER` error in Foundry. We created [this ticket](https://linear.app/chugsplash/issue/CHU-681/fix-foundry-sender-bug-in-foundrys-codebase) to fix it in Foundry.
* We'll add `FOUNDRY_SENDER` back to our logic when we support linked libraries. …
=> fix(pg): check that contracts are deployed in simulation

.changeset/clean-dogs-poke.md, packages/core/src/actions/types.ts, packages/plugins/package.json, packages/plugins/src/cli/types.ts, packages/plugins/src/foundry/utils/index.ts, packages/plugins/src/hardhat/hardhatRunner.ts, packages/plugins/src/hardhat/simulate.ts, packages/plugins/test/mocha/mock.ts
This PR adds additional gas estimate-related data to the ProposalRequest object. This data gives us more flexibility to implement different logic for calculating deployment costs for different networks with different fee formulas or custom RPC methods for calculating fees. 
Note that this PR does not resolve any known cases where we do not accurately estimate deployment costs (optimism, blast, polygon zkevm). I think the best option for handling those cases is to provide more information to the website's backend and then implement the necessary cost calculation logic on the website instead of within the plugin. The main reason why I think this is better is b/c we know of at least one case where a custom RPC method is required to calculate the cost estimates (polygon zkevm) properly. The …
=> feat(pg): Supply more cost estimate data in proposal request

.changeset/clean-chairs-mate.md, packages/core/src/etherscan.ts
Fixes an issue where contracts occasionally fail to be verified on Etherscan when deploying via the DevOps platform. The problem was occurring because sometimes the isVerified function would return true even if the contract wasn't displaying as verified in the Etherscan UI. 
I wasn't originally planning to do this but I've started to notice this issue pretty regularly, especially when running through the quickstart, so I decided to spend a little bit of time investigating it.
Specifically, this issue can happen if the contract is verified implicitly by Etherscan using their internal source code database and not by us calling their API. What seems to be happening is: 
1. We deploy the contract
2. Etherscan indexes the contract and links it to the source code of another already verified …
=> fix(core): Always attempt to verify contracts on Etherscan even if API says it is verified

.changeset/tricky-points-heal.md, packages/contracts/src/types.ts, packages/contracts/src/utils.ts, packages/core/src/actions/execute.ts, packages/core/src/utils.ts, packages/plugins/src/foundry/types.ts, packages/plugins/src/foundry/utils/index.ts, packages/plugins/src/hardhat/simulate.ts, packages/plugins/test/mocha/dummy.ts, packages/plugins/test/mocha/foundry/utils.spec.ts
Updates the build info cache to include deployed bytecode and other relevant fields, which are necessary to implement option 4 in this ticket: [Improve error message when user calls a non-existent function on their script](https://linear.app/chugsplash/issue/CHU-655/improve-error-message-when-user-calls-a-non-existent-function-on-their). Option 4 requires us to make an exact bytecode match on the script's deployed bytecode, but before this PR, it was only possible to check for an exact match on the _init code_ because we didn't store the deployed bytecode in the build info cache.
I added a `_format` field to the build info cache to signify that its structure has changed. I also added logic that handles outdated build info caches for backwards compatibility.
Note: The …
=> fix(pg): update build info cache to include fields for deployed bytecode exact match

.changeset/moody-trees-sing.md, docs/cli-existing-project.md, packages/plugins/src/cli/deploy.ts, packages/plugins/src/cli/propose/index.ts, packages/plugins/src/foundry/options.ts, packages/plugins/src/foundry/utils/index.ts, packages/plugins/src/sample-project/sample-foundry-config.ts
Fixes an issue reported by Sablier where the `Validating Networks...` step is taking an extremely long time to run.
Foundry recently implemented a change where the cache is disregarded if the build info file is requested. This causes a UX issue where if you have build_info = true in your foundry.toml file then the entire project is recompiled every single time you run a script/test/etc. This is obviously a terrible experience. 
https://github.com/foundry-rs/foundry/issues/7379
This causes our plugin to run extremely slow because the users entire project is recompiled every time we call into their script. 
This PR makes the following changes to temporarily address the issue:
1. Remove `build_info = true` from our recommended `foundry.toml` settings 
2. When we call `compile` at the …
=> fix(pg): Avoid recompiling every single time we invoke the users script

.changeset/great-ads-rhyme.md, packages/core/src/utils.ts, packages/plugins/src/hardhat/simulate.ts, packages/plugins/test/mocha/common.ts, packages/plugins/test/mocha/simulate.spec.ts
This PR fixes several issues in the simulation:
* 0xBased ran into a timeout error in his simulation ([ticket](https://linear.app/chugsplash/issue/CHU-805/increase-timeout-in-simulation)). I fixed this by increasing the timeout from 60 seconds to 2.5 mins.
* Any call from a signer wasn't being routed through our provider proxy, so those calls were particularly prone to rate limits. They're now routed through the proxy.
* The backoff period was denominated in milliseconds, when it should've been denominated in seconds (oof)
* An obscure bug that was made a rate limit possible in the proxy. More details in a comment
=> fix(pg): fix simulation bugs

.changeset/slow-rings-compete.md, packages/core/src/utils.ts
This removes the gas limit override on Gnosis and its testnet. It seems that the root issue causing eth_estimateGas to be calculated incorrectly is no longer a problem, so I am removing this. 
I also noticed that setting the high gas limit appears to be causing problems with certain RPC providers that impose limits on the maximum allowed fee for transactions. I was seeing this error:
`tx fee (1.79 ether) exceeds the configured cap (1.00 ether)` 
This occurs because the RPC provider is imposing a limit on the maximum fee transactions they are allowing. This is only an issue on Gnosis Chiado because the gas price has [increased to an extreme level for an unclear reason](https://gnosis-chiado.blockscout.com/gas-tracker). I think this could potentially cause issues during execution if the …
=> fix(core): Remove gas price override on Gnosis

packages/plugins/test/mocha/common.ts
Resolves an issue where one of the simulation tests occasionally fails due to the fork starting slower than usual.
=> fix(pg): Resolve eth mainnet simulation failure

.changeset/eighty-tigers-teach.md, packages/core/src/etherscan.ts
Removes the use of `isVerified()` during the contract verification in favor of matching on the string `already verified` [documented here](https://docs.etherscan.io/contract-verification/common-verification-errors#source-code-already-verified). This also works on Blockscout.
=> fix(core): Remove use of isVerified during contract verification

.changeset/friendly-rivers-hear.md, packages/contracts/src/networks.ts
Previously, we were using a hard-coded Merkle leaf gas value on Moonbeam that was too high. I discovered this when attempting to deploy Mean Finance's `DCAHub`, which caused our batching logic to throw an error because it couldn't fit the corresponding `EXECUTE` leaf into a batch size of 1. This happened because `estimateGasViaManagedService` adds gas in relation to the length of the transaction's calldata. Since the transaction to deploy the `DCAHub` has a lot of calldata, the `estimateGasViaManagedService` function returned an estimated value that was 30k greater than the max batch size, which is 12 million.
This PR fixes the issue by decreasing the Merkle leaf gas value by ~300k. I successfully used the Deploy CLI command to deploy the `DCAHub` on Moonbase Alpha using this new Merkle …
=> fix(ct): Update hard-coded Merkle leaf gas value on Moonbeam

.changeset/curly-rules-boil.md, packages/contracts/contracts/foundry/Sphinx.sol, packages/contracts/src/constants.ts, packages/core/src/utils.ts, packages/plugins/contracts/test/MyContracts.sol, packages/plugins/src/cli/deploy.ts, packages/plugins/src/cli/propose/index.ts, packages/plugins/src/error-messages.ts, packages/plugins/src/foundry/utils/index.ts, packages/plugins/test/mocha/dummy.ts, packages/plugins/test/mocha/error-messages.spec.ts, packages/plugins/test/mocha/fake.ts, packages/plugins/test/mocha/foundry/utils.spec.ts
Multiple users have run into this issue, most recently 0xBased today. See [this ticket](https://linear.app/chugsplash/issue/CHU-389/throw-a-helpful-error-if-contracts-are-too-large) for context.
=> fix(pg): throw an error if contracts are above the size limit

.changeset/gorgeous-tools-smoke.md, packages/demo/package.json
The demo tests are roughly 2 minutes slower after #1628 because each compilation in the test case called "Compiles with viaIR and optimizer enabled" is five seconds slower due to the addition of `SphinxUtils`
=> maint(demo): bump timeout for demo tests

.changeset/early-buses-watch.md, packages/core/src/etherscan.ts
Handles a case where the Etherscan API can return "already verified" after a contract verification has already been submitted. We didn't handle this case correctly, which would cause verification to stall indefinitely.
=> fix(core): Handle already verified response after successful submission

.changeset/violet-numbers-sin.md, packages/contracts/src/networks.ts, packages/core/src/networks.ts, packages/core/src/utils.ts, packages/core/test/utils.spec.ts
Fixes an issue where the hardcoded Merkle leaf gas on Pangolin was greater than the maximum batch on Pangolin. This is a temporary solution. 
I think we should discuss and then implement a better solution that takes into account the variable batch size that is set using the `getMaxGasLimit` function.
=> fix(pg): Lower hardcoded merkle leaf gas on Pangolin

.changeset/slow-cheetahs-perform.md, packages/contracts/src/networks.ts, packages/core/src/actions/execute.ts, packages/core/src/artifacts.ts, packages/core/src/networks.ts
- Adds logic to allow disabling action batching during the execution process.
- Fixes an issue where artifact generation could fail for deployments that involved a large number of transactions. 
- Disables batching on the following networks: Polygon zkevm (and testnet), Linea (and testnet), Moonbeam, Moonriver, Moonbase Alpha, Scroll (and testnet), Rootstock (and testnet), Rari (and testnet), Darwinia Pangolin
- Is a ZK Rollup
- Is in the list of networks on [CHU-861](https://linear.app/chugsplash/issue/CHU-861/investigate-calldata-length-restrictions-on-certain-networks) where the calldata size is a problem
- Is a network where we use a hardcoded merkle leaf gas limit
=> fix(pg): disable polygon zkevm action transaction batching

.changeset/slimy-foxes-smell.md, packages/contracts/contracts/foundry/SphinxUtils.sol, packages/contracts/test/SphinxUtils.t.sol
Removes the depth check from our validation function just in case [this PR is merged in Foundry](https://github.com/foundry-rs/foundry/pull/7632).
=> fix(ct): Remove depth field from Sphinx validate

.changeset/heavy-coats-jam.md, packages/contracts/src/networks.ts, packages/core/src/networks.ts, packages/core/src/utils.ts
Fixes an issue where artifact generation fails if you have previously deployed on any networks that have been deprecated.
=> fix(pg): Allow generating artifacts for deprecated networks

.changeset/gorgeous-lobsters-tap.md, .changeset/rare-toys-obey.md, packages/contracts/src/networks.ts, packages/core/src/actions/types.ts, packages/plugins/src/foundry/utils/index.ts
We still need this data to properly estimate the cost of deployments on OP stack networks, but we should not supply it this way via proposals because we can exceed the request size limit in extreme cases. I thought this was quite unlikely to occur, but this is what happened with Centrifudges deployment. I will need to reconsider how to go about estimating the deployment cost on OP stack chains without having this data immediately available in the proposal API endpoint. 
Note that this change is *not* required to unblock Centrifuge, I resolved their issue with a minor change on the website. This PR eliminates the possibility of it happening to anyone else. 
As a precaution, I tested out deploying on the testnets of all the networks Centrifuge wants to deploy on. I found that the calldata …
=> fix(pg): Remove tx data from proposal request

.changeset/poor-bats-draw.md, packages/core/src/artifacts.ts, packages/core/src/utils.ts
Causes API errors to be passed through to the console if the response code is unexpected. This should help with debugging API-related issues that are hard to reproduce.
=> fix(pg): Pass through error if API response unexpected

packages/contracts/test/ManagedService.t.sol
This fixes a minor issue in one of our tests that was introduced by this [PR in Foundry](https://github.com/foundry-rs/foundry/pull/7653). This issue does not effect our service for any users.
=> maint(ct): Fix test broken by Foundry update

.changeset/calm-wombats-cross.md, packages/contracts/src/networks.ts, packages/core/src/actions/types.ts, packages/core/test/convert.spec.ts, packages/plugins/src/foundry/utils/index.ts
Fills in rollup stack information for relevant networks. This is useful for making sure our cost estimates are accurate on the website.
=> feat(pg): Include rollup stack information on all relevant networks

.changeset/tricky-chefs-fail.md, packages/plugins/src/foundry/utils/index.ts
New versions of foundry do not allow the usage of both the `--json` and `--silent` flags. Using them both results in an error message. The `--silent` flag is now implied by the `--json` flag.
- Bug fix (non-breaking change which fixes an issue)
Using existing tests.
=> fix(pg): no longer use `--json` and `--quiet` for forge scripts

.changeset/nine-ligers-approve.md, packages/plugins/src/foundry/utils/index.ts
Instead of slicing into the `libraryVersion` string we now replace quotes, this makes it so if there are no quotes it doesn't remove/replace anything.
#1732 
New versions of foundry no longer have the version double quoted, this PR makes it so it works for both the older versions of foundry as well as the newer versions.
-
=> fix: `libraryVersion` quote slicing

packages/core/test/convert.spec.ts, packages/demo/test/Solc.spec.ts, packages/demo/test/init.spec.ts, packages/plugins/src/foundry/utils/index.ts, packages/plugins/test/mocha/cli/propose.spec.ts
Since there currently is no instance of the hosted platform and some testnets have been deprecated and thus no longer have available RPCs, we are disabling some tests that rely on these (for now).
=> ci: disable tests that rely on live networks and a hosted instance 
