sphinx-labs/sphinx

- .changeset/two-pugs-heal.md
- packages/contracts/contracts/ChugSplashRegistry.sol
Standardizes the style of the ChugSplashRegistry using Seaport-style
comments.
> style(ct): standardize ChugSplashRegistry style

- .circleci/config.yml
For now, always run CI on every PR.
> fix(ci): always run CI

- .github/mergify.yml
Fixes mergify.yml to merge, not squash, when merging into main.
> fix(ci): merge not squash on main

- .changeset/proud-colts-tickle.md
- packages/executor/hardhat.config.ts
- packages/executor/package.json
- packages/executor/src/index.ts
- packages/executor/src/utils/compile.ts
- packages/executor/src/utils/constants.ts
- packages/executor/src/utils/helpers.ts
- packages/executor/src/utils/index.ts
- yarn.lock
Updates the ChugSplash executor service to include the basic execution
flow. Many components are missing and need to be added to smart
contracts before this will work, but the foundation is there.
> feat(exec): add basic execution flow

- .changeset/unlucky-coins-mix.md
- packages/core/src/actions/types.ts
- packages/plugins/package.json
- packages/plugins/src/hardhat/tasks.ts
- yarn.lock
> feat(pg): add hardhat task for displaying status of live upgrade

- .changeset/mean-dragons-drive.md
- package.json
- packages/contracts/contracts/ChugSplashManager.sol
- packages/contracts/contracts/IExecutorSelectionStrategy.sol
> feat(ct): add executor selection to Manager

- packages/executor/src/index.ts
Adds some TODOs to the executor codebase.
> docs(exec): add some todos

- specs/chugsplash-manager.md
Adds a "speedspec" for the ChugSplashManager. This includes all of the key details without any fluff.
> feat(specs): ChugSplashManager speedspec

- specs/chugsplash-manager.md
Updates the ChugSplashManager speedspec to prevent people from using the contracts in the middle of an upgrade. The steps to do this are:
1. Shut down every proxy by setting their implementations to address(0).
2. Call all the `SET_STORAGE` and `DEPLOY_IMPLEMENTATION` actions in calls to `executeChugSplashAction`.
3. Upgrade all proxies to their new implementations in a single `SET_IMPLEMENTATIONS` transaction, which must be the last action in the bundle.'
Also changes the casing of `EXECUTOR_BOND_AMOUNT` and `EXECUTION_LOCK_TIME` from camel case.
Lastly, changes `BUNDLE_EXECUTION_BOND_AMOUNT` to `OWNER_BOND_AMOUNT` since I thought this was a more appropriate name.
> fix(specs): update manager speedspec with new action type

- .changeset/smart-apes-jump.md
- packages/plugins/src/hardhat/artifacts.ts
Adds support for foundry-hardhat style artifacts which require a shorthand name instead of the long file name.
> feat(plg): add support for foundry-hardhat

- .changeset/clever-games-destroy.md
- packages/plugins/package.json
- packages/plugins/src/hardhat/predeploys.ts
- packages/plugins/src/hardhat/tasks.ts
Removes reliance on hardhat-deploy for local system deployment.
> feat(plg): remove hardhat-deploy

- .gitignore
- packages/core/Untitled-1
Minor tweak to the gitignore and removes an unnecessary file.
> fix(meta): tweak gitignore

- .changeset/olive-waves-own.md
- packages/core/src/languages/solidity/storage.ts
- packages/plugins/.gitignore
- packages/plugins/chugsplash/SimpleStorage.config.ts
- packages/plugins/contracts/SimpleStorage.sol
- packages/plugins/hardhat.config.ts
- packages/plugins/package.json
- packages/plugins/src/hardhat/deployments.ts
- packages/plugins/test/SimpleStorage.spec.ts
- Adds support for mappings, including nested mappings and structs
- Adds a basic automated integration test suite to the plugins package
> Add Support for Mapping Types

- .changeset/angry-games-double.md
- .changeset/perfect-ants-build.md
- .changeset/unlucky-wolves-work.md
- packages/contracts/src/ifaces.ts
- packages/core/src/config/parse.ts
- packages/executor/.env.example
- packages/executor/Dockerfile
- packages/executor/package.json
- packages/plugins/dev.ts
- packages/plugins/src/hardhat/deployments.ts
- packages/plugins/src/hardhat/tasks.ts
- packages/plugins/src/hardhat/utils.ts
1. In /plugins: `npx hardhat node --setup-internals`
2. In /executor: `yarn start`
3. In /plugins: `npx hardhat run --disable-chugsplash --network localhost dev.ts`
> fix(pg): add script that commits local deployments to IPFS

- .changeset/mighty-geese-tan.md
- packages/contracts/contracts/ChugSplashManager.sol
- packages/contracts/src/ifaces.ts
- packages/plugins/src/hardhat/deployments.ts
Error was discovered in [this transaction](https://goerli-optimism.etherscan.io/tx/0x6653a058d740cbdb88c2b1fca08dee17998bd997cd36c59a6680b5a3cb980971#internal) (note the failed create2 call)
> fix(ct): fix out-of-gas bug for implementation contract deployments

- packages/plugins/src/hardhat/deployments.ts
- packages/plugins/src/hardhat/tasks.ts
Adds spinner output for upgrades as per [this comment](https://github.com/chugsplash/chugsplash/pull/254/files#r1033981244).
> spinner logic for upgrades

- .changeset/hot-donuts-hear.md
- packages/core/src/utils.ts
- packages/plugins/package.json
- packages/plugins/src/hardhat/deployments.ts
- packages/plugins/src/hardhat/tasks.ts
- packages/plugins/test/Storage.spec.ts
- packages/plugins/test/constants.ts
- yarn.lock
Merges the deployment and upgrade tasks. I did this by updating the `checkValidDeployment` function to instead check if an upgrade is happening or not. If an upgrade is happening, then we check if the it is valid and confirm that the user intends to perform an upgrade of their project before continuing with the deployment.
> Merge deploy and upgrade tasks

- .changeset/breezy-pigs-deny.md
- packages/core/src/config/parse.ts
- packages/core/src/config/types.ts
- packages/core/src/utils.ts
- packages/demo/chugsplash/SimpleStorage.config.ts
- packages/executor/src/utils/etherscan.ts
- packages/plugins/src/hardhat/artifacts.ts
- packages/plugins/src/hardhat/deployments.ts
Removes ambiguity since "address" could be interpreted as the implementation or proxy address.
> fix(core): change ContractConfig "address" field to "proxy"

- .changeset/wicked-paws-bathe.md
- packages/plugins/src/hardhat/artifacts.ts
Fixes a few bugs in the format of the deployment artifacts that were being generated. These bugs created incompatibilities with strongly typed tooling.
> fix(plg): bugs in generated artifact format

- .changeset/gorgeous-laws-work.md
- packages/core/src/actions/execute.ts
- packages/core/src/actions/types.ts
Updates batch action execution with helper functions that figure stuff out automatically to reduce the number of things that need to be hard-coded. Now also batch executes implementation deployments.
> feat(core): smarter batch action execution

- .changeset/tall-swans-do.md
- packages/core/src/utils.ts
- packages/plugins/src/hardhat/tasks.ts
Adds `chugsplash-list-proposers` and `chugsplash-add-proposer`
> feat(pg) Add list-proposers and add-proposers tasks

- README.md
> docs: slight fix to main readme

- .changeset/selfish-buckets-greet.md
- packages/core/src/config/parse.ts
- packages/core/src/config/types.ts
- packages/plugins/chugsplash/Storage.config.ts
- packages/plugins/src/hardhat/utils.ts
- packages/plugins/test/Storage.spec.ts
Changes contract reference syntax from `{ '!Ref': <contractName> }` to `'{{ <contractName }}'`
> fix(core): change contract reference syntax

- .changeset/seven-teachers-sneeze.md
- packages/core/src/languages/solidity/storage.ts
- packages/plugins/contracts/Storage.t.sol
- packages/plugins/test/Storage.spec.ts
- packages/plugins/test/constants.ts
Adds support for bytes/strings of length > 31
> feat(core): support bytes/strings (length >31)

- .changeset/large-dolls-smile.md
- packages/core/src/actions/artifacts.ts
- packages/core/src/actions/bundle.ts
- packages/core/src/config/parse.ts
- packages/core/src/config/types.ts
- packages/core/src/execution/index.ts
- packages/core/src/fund.ts
- packages/core/src/languages/solidity/compiler.ts
- packages/core/src/languages/solidity/predeploys.ts
- packages/core/src/languages/solidity/storage.ts
- packages/core/src/tasks/index.ts
- packages/core/src/utils.ts
- packages/plugins/src/hardhat/deployments.ts
- packages/plugins/src/hardhat/tasks.ts
- tsconfig.json
Annoying in the short term, but should cause fewer bugs in the long term.
https://www.typescriptlang.org/tsconfig#strictNullChecks
> fix(core): set `strictNullChecks` to true for TypeScript

- .changeset/silent-ducks-press.md
- packages/core/src/messages/index.ts
- packages/core/src/tasks/index.ts
- Fills in some foundry specific outputs
- Fixes some cases where outputs in foundry reference hardhat
> fix(core): Add foundry specific messages

- .changeset/hungry-items-study.md
- packages/core/src/tasks/index.ts
- packages/executor/src/index.ts
Fixes an issue where the executor was always trying to execute locally even when running as a standalone process.
> fix(exec): Fix bug where executor always tries to execute locally

- .changeset/slow-buckets-watch.md
- packages/core/src/analytics.ts
Adds timeouts to the analytics function calls. This prevents our functions from hanging if the analytics service is not functioning properly and/or the user is not connected to the internet.
> fix(core): Add timeout on analytics functions

- .changeset/kind-jobs-dress.md
- packages/core/src/tasks/index.ts
Adds a link to the discord after completing a deployment
> feat(pg): Add discord link output

- .changeset/fuzzy-trainers-bow.md
- packages/core/src/tasks/index.ts
Minor tweak to ether formatting, 4 decimals is more than enough for these log lines.
> fix(core): 4 decimal ether formatting

- docs/foundry/getting-started.md
> fix(docs): Update foundry getting started to include installing the stringutils dependency

- packages/contracts/package.json
- packages/core/src/languages/solidity/compiler.ts
- packages/plugins/foundry.toml
- packages/plugins/package.json
- packages/plugins/remappings.txt
Enables tests in the CI process for both the plugins and contracts packages
> ci: Enable Tests in CI

- packages/contracts/package.json
- packages/core/src/languages/solidity/compiler.ts
- packages/plugins/foundry.toml
- packages/plugins/package.json
- packages/plugins/remappings.txt
Reverts chugsplash/chugsplash#484
> Revert "ci: Enable Tests in CI"

- .changeset/old-ads-care.md
- packages/plugins/package.json
- packages/plugins/src/index.ts
- packages/plugins/src/internal-tasks.ts
Useful for unit testing the `ChugSplashManager`
> fix(pg): add internal task for displaying bundles

- .changeset/silly-cats-float.md
- packages/core/src/languages/solidity/predeploys.ts
- packages/core/src/types.ts
- packages/executor/.env.example
- packages/executor/src/index.ts
- packages/executor/src/utils/child.ts
- packages/executor/src/utils/execute.ts
- packages/plugins/src/executor.ts
- packages/plugins/src/foundry/index.ts
- packages/plugins/src/hardhat/tasks.ts
Adds support for parallel execution in a single executor instance. This is quite a bit more efficient than running multiple executors and also allows for easier local testing of parallel execution.
> feat(exec): Implement Parallel Execution

- .changeset/fuzzy-years-report.md
- .changeset/soft-chicken-know.md
- packages/core/src/constants.ts
- packages/executor/package.json
- packages/executor/src/index.ts
- packages/executor/src/utils/etherscan.ts
- packages/executor/src/utils/execute.ts
- Fixes an issue where ChugSplash internal contracts where not verified correctly
- Fixes an issue where user contracts were not verified correctly
- Fixes an issue where the executor retry logic fails after completing the maximum number of retries
> fix(exec): Etherscan Verification Bugs

- .changeset/clean-rings-clap.md
- packages/contracts/contracts/ChugSplashManager.sol
- packages/contracts/contracts/libraries/MerkleTree.sol
- packages/contracts/src/ifaces.ts
- packages/plugins/chugsplash/hardhat/TransparentUpgradableUpgrade.config.ts
- packages/plugins/chugsplash/hardhat/UUPSAccessControlUpgradableUpgrade.config.ts
- packages/plugins/chugsplash/hardhat/UUPSOwnableUpgradableUpgrade.config.ts
Small gas optimization for loop
- wrap i++ in unchecked block
- allocate the length of the array to memory to not have to calculate the length at each loop
> gas optimization for loop

- .changeset/modern-hotels-taste.md
- packages/contracts/src/ifaces.ts
- packages/plugins/chugsplash/hardhat/TransparentUpgradableUpgrade.config.ts
- packages/plugins/chugsplash/hardhat/UUPSAccessControlUpgradableUpgrade.config.ts
- packages/plugins/chugsplash/hardhat/UUPSOwnableUpgradableUpgrade.config.ts
- packages/plugins/test/constants.ts
Adds handling to resolve build info file paths automatically
> maint(ct): Resolve build info files automatically

- packages/core/src/actions/bundle.ts
- packages/core/src/languages/solidity/storage.ts
- packages/core/src/utils.ts
See [here](https://github.com/chugsplash/chugsplash/pull/553#issuecomment-1465075953) for an explanation.
> fix(core): use solidity-ast to get the underlying user-defined type

- .changeset/stale-forks-listen.md
- packages/contracts/contracts/ChugSplashManager.sol
Adds the proposer address to the bundle proposed event.
> feat(ct): Add proposer address to bundle proposed event

- .changeset/lovely-bears-look.md
- packages/core/src/languages/solidity/iterator.ts
- packages/plugins/chugsplash/foundry/deploy.t.js
- packages/plugins/contracts/Storage.sol
- packages/plugins/test/Storage.spec.ts
- packages/plugins/test/constants.ts
Fix bug where using an address payable causes an error to be thrown during encoding.
> fix(core): Fix bug encoding address payable

- .changeset/heavy-bears-hug.md
- packages/core/src/actions/artifacts.ts
- packages/core/src/actions/bundle.ts
- packages/core/src/config/parse.ts
- packages/core/src/execution/index.ts
- packages/core/src/tasks/index.ts
- packages/core/src/utils.ts
> fix(core): write separate artifacts for proxy and implementation contracts

- packages/demo/hardhat.config.ts
- packages/plugins/hardhat.config.ts
- packages/plugins/package.json
Removes a few things that were previously necessary due to being over the contract size limit which is no longer the case.
> maint(pg): Remove unlimited contract size logic

- .changeset/tidy-snails-thank.md
- packages/core/src/config/parse.ts
- packages/core/src/utils.ts
- packages/plugins/chugsplash/NoProxyContractReference.config.ts
- packages/plugins/chugsplash/Storage.config.ts
- packages/plugins/chugsplash/VariableValidation.config.ts
- packages/plugins/chugsplash/foundry/addProposer.t.js
- packages/plugins/chugsplash/foundry/cancel.t.js
- packages/plugins/chugsplash/foundry/claim.t.js
- packages/plugins/chugsplash/foundry/claimProposeFundApprove.t.js
- packages/plugins/chugsplash/foundry/deploy.t.js
- packages/plugins/chugsplash/foundry/transfer.t.js
- packages/plugins/chugsplash/foundry/withdraw.t.js
- packages/plugins/contracts/SimpleStorage.sol
- packages/plugins/contracts/Stateless.sol
- packages/plugins/src/foundry/index.ts
- packages/plugins/src/hardhat/deployments.ts
- packages/plugins/test/Storage.spec.ts
- packages/plugins/test/Validation.spec.ts
Adds support for contract references in constructor arguments with the exception of references to no-proxy contracts within other no-proxy contracts
> feat(core): Contract references in constructor arguments

- packages/core/src/utils.ts
Uses hardhat_impersonateAccount to detect if the target network is a local or live network.
> fix(core): Detect local networks with hardhat_impersonateAccount

- packages/contracts/contracts/ChugSplashManager.sol
Previously, in the ChugSplashManager's `initiateExecution` function, the expected default proxy address was calculated based on a call to `getDefaultProxyAddress`. This is unnecessary since `target.proxy` contains the expected address. This PR removes the unnecessary call to `getDefaultProxyAddress`.
> maint(ct): use default proxy address from the `target` object

- packages/contracts/contracts/ChugSplashDataTypes.sol
- packages/contracts/contracts/ChugSplashManager.sol
- packages/core/src/actions/bundle.ts
- packages/core/src/actions/types.ts
- packages/core/src/config/parse.ts
- packages/core/src/config/types.ts
- packages/core/src/etherscan.ts
- packages/core/src/fund.ts
- packages/core/src/tasks/index.ts
- packages/core/src/utils.ts
- packages/executor/src/utils/execute.ts
- packages/plugins/src/hardhat/artifacts.ts
- packages/plugins/test/Transfer.spec.ts
This is more accurate since the address can be referring to a stateless immutable contract.
> maint(core): change parsed config proxy field to address

- packages/contracts/contracts/ChugSplashRegistry.sol
Will format the NatSpec docs in a later PR.
> docs(ct): update registry docs

- packages/contracts/contracts/ChugSplashDataTypes.sol
- packages/contracts/contracts/ChugSplashManager.sol
- packages/contracts/contracts/ChugSplashManagerProxy.sol
- packages/contracts/contracts/DefaultGasPriceCalculator.sol
- packages/contracts/contracts/ManagedService.sol
- packages/contracts/contracts/Semver.sol
- packages/contracts/contracts/interfaces/IChugSplashManager.sol
- packages/contracts/contracts/interfaces/IGasPriceCalculator.sol
Haven't made them look pretty yet
> docs(ct): finish contract natspec docs

- specs/README.md
Inspired by [Optimism's specs](https://github.com/ethereum-optimism/optimism/tree/develop/specs)
> docs(specs): spec readme

- packages/contracts/src/constants.ts
Temporarily replaces the multisig address with an EOA
> fix(core): Update owner address to be EOA

- README.md
- docs/chugsplash-file.md
- docs/ci-integration.md
- docs/foundry/getting-started.md
- docs/hardhat/setup-project.md
- docs/live-network.md
Updates docs to cover major changes since our last release.
> docs: Update docs for new release

- docs/ci-integration.md
- packages/core/package.json
- packages/demo/package.json
- packages/executor/package.json
- packages/plugins/package.json
- yarn.lock
- Fixes an issue where the executors dependency on the contracts package wasn't properly bumped
- Fixed some inaccuracies in the ci integration documentation
> Fix(executor): Fix incorrect contract package version

- packages/core/src/metatxs.ts
- yarn.lock
Adds some additional handling when the relayer responds with an error.
> feat(core): Add better relayer error handling

- .github/workflows/release.yml
Removes some deprecated dependencies in the release process. 
This is a pretty simple change, but it won't be tested until the next time we do a release so we should just be aware we might need to address issues with this then.
> fix(ci): Update release process dependencies

- packages/plugins/foundry-contracts/ChugSplash.sol
- packages/plugins/foundry.toml
- Fixes a variety of bugs in the execution logic
- Uses `utils.msgSender()` to handle fetching the correct deployer address in all cases
> Fix execution logic bugs

- packages/plugins/src/foundry/get-bundle-info.ts
We need this to generate deployment artifacts. Technically we should be able to use `vm.readCallers()` (https://book.getfoundry.sh/cheatcodes/read-callers?highlight=readCaller#readcallers) to only do this write when broadcasting, but I was unable to get that working as of now.
> Write Canonical Config

- .github/workflows/release.yml
Fixes an issue with the release process due to updating a deprecated dependency.
> fix(ci): Fix release workflow

- .changeset/metal-otters-draw.md
- packages/plugins/src/foundry/utils/index.ts
- packages/plugins/src/sample-project/index.ts
- packages/plugins/src/sample-project/sample-contract.ts
Fixes some issues with the sample foundry project.
> fix(pg): Fix bugs in sample project generation

- ops/ci-builder/Dockerfile
This is just a sanity check to ensure that our CI process will publish a Dockerfile when it's changed.
> chore: update dockerfile

- .changeset/few-tips-accept.md
- packages/plugins/chugsplash/Storage.config.ts
- packages/plugins/contracts/foundry/ChugSplash.sol
- packages/plugins/contracts/test/ContainsStorage.sol
- packages/plugins/test/Storage.spec.ts
- packages/plugins/test/constants.ts
- packages/plugins/test/foundry/ChugSplash.t.sol
Fixes an issue where the ChugSplash foundry library fails to compile when the optimizer is disabled.
> Fix compilation issue when optimizer disabled

- .changeset/shaggy-meals-change.md
- package.json
- packages/contracts/contracts/ChugSplashDataTypes.sol
- packages/contracts/contracts/ChugSplashFunder.sol
- packages/contracts/contracts/ChugSplashLZReceiver.sol
- packages/contracts/contracts/Import.sol
- packages/contracts/foundry.toml
- packages/contracts/package.json
- packages/contracts/src/ifaces.ts
- packages/contracts/test/Funder.t.sol
- packages/core/src/addresses.ts
- packages/core/src/constants.ts
- packages/core/src/contract-info.ts
- packages/core/src/etherscan.ts
- packages/core/src/languages/solidity/predeploys.ts
- packages/plugins/package.json
- packages/plugins/script/write-constants.ts
- packages/plugins/src/foundry/index.ts
- yarn.lock
Adds cross-chain funding contracts
> feat(ct): Add crosschain funding contract

- .github/cla/entity.md
- .github/cla/fiduciary.md
> docs: Add CLA

- .changeset/beige-rabbits-kick.md
- docs/ci-foundry-proposals.md
- docs/ci-hardhat-proposals.md
- docs/config-file.md
- docs/ops-foundry-getting-started.md
- docs/ops-hardhat-getting-started.md
- packages/core/src/tasks/index.ts
- packages/plugins/foundry.toml
- packages/plugins/hardhat.config.ts
- packages/plugins/package.json
- packages/plugins/src/cli/index.ts
- packages/plugins/src/hardhat/tasks.ts
- packages/plugins/test/MultiChain.spec.ts
- packages/plugins/test/constants.ts
- packages/plugins/test/helpers.ts
- packages/plugins/test/kill-hh-nodes.sh
- packages/plugins/test/run-hh-tests.sh
- yarn.lock
- Adds the dry run and confirm flags to the propose task
- Adds docs for integrating into CI
> feat(pg): Add dry run and confirm flags to the propose task

- .changeset/witty-snakes-trade.md
- README.md
- docs/ci-foundry-proposals.md
- docs/ci-hardhat-proposals.md
- packages/core/src/tasks/index.ts
- Output a more accurate message when dry running
- More fixed for CI integration docs
> fix(core): Output more accurate log when dry running

- .changeset/tall-buckets-pull.md
- packages/core/src/actions/bundle.ts
- packages/core/src/config/fetch.ts
- packages/core/src/config/parse.ts
- packages/core/src/config/types.ts
- packages/core/src/tasks/index.ts
- packages/core/src/utils.ts
- packages/executor/src/utils/execute.ts
- packages/executor/test/Executor.spec.ts
- packages/plugins/src/foundry/get-bundle-info.ts
- packages/plugins/test/MultiChain.spec.ts
- packages/plugins/test/helpers.ts
- packages/plugins/test/run-hh-tests.sh
Reverts sphinx-labs/sphinx#948
> Revert "feat(exec): Do not recompile during execution"

- .changeset/good-mangos-mate.md
- packages/core/hardhat.config.ts
- packages/core/src/actions/bundle.ts
- packages/core/src/constants.ts
- packages/core/src/etherscan.ts
- packages/core/src/languages/solidity/predeploys.ts
- packages/core/src/networks.ts
- packages/core/src/utils.ts
- packages/plugins/hardhat.config.ts
- packages/plugins/test/MultiChain.spec.ts
> feat(pg): Support fantom, polygon zkevm, avalanche, and linea

- .changeset/brave-chairs-lay.md
- packages/core/src/tasks/index.ts
- packages/core/src/utils.ts
- yarn.lock
Minor bug fixed for multisig support
> feat(pg): Integrate multisig support with website

- .changeset/olive-windows-kiss.md
- docs/constructor-args.md
- packages/core/src/actions/bundle.ts
- packages/core/src/config/parse.ts
- packages/core/src/config/types.ts
- packages/core/src/etherscan.ts
- packages/core/src/networks.ts
- packages/plugins/contracts/test/ConstructorArgOverrides.sol
- packages/plugins/hardhat.config.ts
- packages/plugins/sphinx/ChainOverrides.config.ts
- packages/plugins/sphinx/validation/ConstructorArgValidation.config.ts
- packages/plugins/sphinx/validation/OverrideArgValidation.config.ts
- packages/plugins/src/foundry/get-bundle-info.ts
- packages/plugins/src/foundry/structs.ts
- packages/plugins/test/ChainOverrides.spec.ts
- packages/plugins/test/Validation.spec.ts
- packages/plugins/test/constants.ts
- packages/plugins/test/kill-hh-nodes.sh
- packages/plugins/test/run-hh-tests.sh
Add support for constructor arg overrides
> feat(pg): Support constructor arg overrides

- docs/ci-foundry-proposals.md
Added an instruction detailing where to copy paste the propose code.
> feat(README): add deploy copy paste instruction in ci tutorial

- packages/contracts/scripts/output-deployment-merkle-tree.ts
- packages/contracts/src/merkle-tree.ts
- Fixes an issue where [we did not check the form of `NetworkDeploymentData.tx`](https://github.com/spearbit-audits/review-sphinx-labs/pull/4#discussion_r1404324577).
> fix(mt): Check NetworkDeploymentData.tx form

- .changeset/sour-feet-reflect.md
- packages/core/src/networks.ts
- packages/plugins/test/mocha/artifacts.spec.ts
- packages/plugins/test/mocha/common.ts
- packages/plugins/test/mocha/simulate.spec.ts
This PR adds a test that checks that the simulation works on all supported live networks. I manually checked that this test would have caught [this bug caused by fluctuating gas prices](https://github.com/sphinx-labs/sphinx/pull/1308) and [this bug caused by a high block gas limit](https://github.com/sphinx-labs/sphinx/pulls?q=is%3Apr+is%3Aclosed)
> test(pg): test that the simulation works on all supported live networks

- .changeset/late-dots-sip.md
- docs/cli-existing-project.md
- packages/plugins/src/sample-project/sample-foundry-config.ts
- Includes some minor updates to the existing project guide
- Updates the recommended `fs_permissions` configuration option to be less invasive
> fix(docs): Update integration guide env variables and fs_permission configuration

- .changeset/bright-balloons-camp.md
- packages/plugins/src/cli/install/index.ts
- packages/plugins/src/cli/setup.ts
Adds the `sphinx install` command to the CLI.
> feat(pg): Add sphinx install command

- packages/contracts/contracts/foundry/Sphinx.sol
- packages/contracts/contracts/foundry/SphinxPluginTypes.sol
- packages/core/src/config/types.ts
- packages/plugins/src/cli/deploy.ts
- packages/plugins/src/cli/propose/index.ts
- packages/plugins/src/cli/utils.ts
- packages/plugins/src/foundry/decode.ts
- packages/plugins/test/mocha/common.ts
Adds logic to the propose and deploy commands to detect if the version of the sphinx library contracts does not match the version required by the CLI.
> feat(pg): Detect version drift in contracts library

- docs/cli-existing-project.md
- packages/demo/test/Solc.spec.ts
- packages/demo/test/init.spec.ts
- packages/plugins/src/cli/install/index.ts
- packages/plugins/src/cli/setup.ts
- packages/plugins/src/sample-project/index.ts
- Updates the docs to match the new installation scheme. 
- Fixes a number of issues I noticed during integration.
> docs: Update integration docs

- packages/contracts/scripts/write-version.ts
Fixes a circular dependency in the `write-version.ts` script which prevents the release process from working properly.
> fix(ci): Fix circular dependency in write-version script

- docs/cli-existing-project.md
Fixes some minor issues with the installation guide.
> fix(docs): Update recommended dep installation location

- README.md
- docs/configuration-options.md
- packages/contracts/contracts/foundry/SphinxConstants.sol
- packages/contracts/src/networks.ts
- packages/core/src/actions/execute.ts
- packages/core/src/actions/types.ts
- packages/core/src/networks.ts
- packages/core/src/utils.ts
- packages/core/test/convert.spec.ts
Adds support for Rootstock. I did not add support for the Rootstock testnet because I was not able to find a reliable node provider that supported all the RPC methods we require.
> feat(pg): Support Rootstock

- .changeset/olive-sheep-know.md
Triggers a release for the plugins package
> fix(pg): Trigger release for new networks

- .changeset/three-pumas-sort.md
- README.md
- packages/contracts/contracts/foundry/SphinxConstants.sol
- packages/contracts/src/networks.ts
- packages/core/test/convert.spec.ts
Adds support for Zora and Rari
> feat(pg): Support Zora and Rari

- packages/contracts/src/networks.ts
Adds the network display names used on the website to the networks array
> feat(ct): Add display name to networks array

- ops/ci-builder/Dockerfile
Fixes the CI builder foundry fork installation process.
> fix(ci): Fix fork installation in ci builder

- packages/plugins/src/cli/deploy.ts
- packages/plugins/src/cli/propose/index.ts
- packages/plugins/src/foundry/options.ts
- packages/plugins/src/foundry/types.ts
Adds checks for the required foundry.toml options.
> feat(pg): Check if create2 factory option not enabled

- .changeset/great-pots-yell.md
Makes the update to the contracts package a minor change.
> fix: Make contracts update a minor change

- .changeset/tough-teachers-glow.md
> maint(core): Trigger release

- packages/demo/package.json
- packages/demo/test/Solc.spec.ts
- yarn.lock
Uses a limited batch size when compiling in the demo tests to prevent the process from timing out due to running out of memory. I found that this didn't slow down the demo test suite too much, so I kept it enabled for all PRs.
> fix(ci): Stop demo tests from failing

- .changeset/nervous-kids-yawn.md
Trigger a release in the contracts package
> fix(ct): Trigger release

- .changeset/weak-crews-flash.md
- docs/cli-existing-project.md
- docs/writing-scripts.md
- packages/contracts/contracts/foundry/Sphinx.sol
- packages/contracts/contracts/foundry/SphinxUtils.sol
- packages/plugins/src/cli/deploy.ts
- packages/plugins/src/cli/propose/index.ts
- packages/plugins/src/foundry/options.ts
- packages/plugins/src/foundry/utils/index.ts
- packages/plugins/src/sample-project/sample-foundry-config.ts
- Sets `FOUNDRY_SENDER` and `ETH_FROM` during collection phase.
- Sets the `--always-use-create-2-factory` cli flag during collection phase.
> feat(pg): Collection deployment options

- ops/ci-builder/Dockerfile
Switches us off the Foundry fork in our CI process.
> fix(ci): Switch off fork in CI process

- .changeset/two-shoes-pull.md
- docs/cli-existing-project.md
- docs/configuration-options.md
- docs/writing-scripts.md
- packages/contracts/contracts/foundry/Sphinx.sol
- packages/contracts/contracts/foundry/SphinxUtils.sol
- packages/contracts/test/ScriptConfiguration.t.sol
- packages/contracts/test/SphinxTestUtils.sol
- packages/contracts/test/SphinxUtils.t.sol
- packages/plugins/contracts/test/script/Cases.s.sol
- packages/plugins/contracts/test/script/Empty.s.sol
- packages/plugins/contracts/test/script/Large.s.sol
- packages/plugins/contracts/test/script/PartiallyEmpty.s.sol
- packages/plugins/contracts/test/script/RevertDuringSimulation.s.sol
- packages/plugins/contracts/test/script/Simple.s.sol
- packages/plugins/script/Sample.s.sol
- packages/plugins/src/sample-project/sample-contracts.ts
Allow configuration via a new `configureSphinx()` function
> feat(pg): Allow configuration via configureSphinx() function

- .changeset/large-lemons-burn.md
- packages/plugins/src/hardhat/simulate.ts
The [original PR](https://github.com/sphinx-labs/sphinx/commit/3e720bb270afe9dd6a3feaf60be50a81a1e22016)
> fix(pg): re-introduce continuing with rate limits

- .changeset/warm-trainers-fly.md
- packages/contracts/src/networks.ts
- packages/contracts/test/mocha/moonbeam-gas.spec.ts
- Removes the -200 per byte on Moonbeam
> fix(pg): Remove storage gas cost subtraction on Moonbeam

- .changeset/clever-pans-cross.md
- packages/plugins/src/cli/deploy.ts
- packages/plugins/src/cli/propose/index.ts
Do not force recompile when running propose/deploy command.
> fix(pg): Do not force recompile during propose or deploy

- .changeset/brown-singers-taste.md
- packages/contracts/src/networks.ts
Increases the Drippie drip size on Sepolia to better handle gas price spikes.
> fix(ct): Increase Sepolia drip size to handle gas spikes

- packages/contracts/contracts/foundry/SphinxConstants.sol
- packages/contracts/contracts/foundry/SphinxUtils.sol
- packages/contracts/test/Sphinx.t.sol
- packages/contracts/test/SphinxTestUtils.sol
- packages/core/src/preview.ts
- packages/core/test/preview.spec.ts
Adds in logic to include an action that checks the balance of the safe if the user requests funding for the Safe.
> feat(pg): Add execute action to confirm funds airdropped to Safe

- packages/plugins/src/foundry/utils/index.ts
- packages/plugins/test/mocha/cli/propose.spec.ts
Allows proposals and deployments against local nodes when an environment variable is configured.
> feat(pg): Allow proposals against local nodes with env variable

- ops/ci-builder/Dockerfile
- packages/core/src/config/types.ts
- packages/plugins/test/mocha/foundry/utils.spec.ts
- Bumps the foundry version used in our CI process
- Fixes an issue in our tests that was broken by an update in foundry
> maint(ci): Bump docker container version

- .github/workflows/docker-image.yml
- ops/ci-builder/check-changed.sh
Builds and publishes our CI builder once per day at 2 am UTC.
> feat(ci): Update CI container daily

- docs/breaking/registration.md
Reverts sphinx-labs/sphinx#1703
> Revert "fix(docs): Include lock file read access in migration guide"
